// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using Spilton.Api.Data;

#nullable disable

namespace Spilton.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260910035814_AddPreparationSpaces")]
    partial class AddPreparationSpaces
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Spilton.Api.Chat.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SpaceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SpaceId");

                    b.HasIndex("UserId", "UpdatedAt", "Id");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("Spilton.Api.Chat.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CitationsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(32000)
                        .HasColumnType("character varying(32000)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<Guid[]>("DocumentIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<bool>("IsSuperseded")
                        .HasColumnType("boolean");

                    b.Property<string>("ModelName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ModelProvider")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid?>("ReplyToId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "Sequence")
                        .IsUnique();

                    b.ToTable("Messages", t =>
                        {
                            t.HasCheckConstraint("CK_Message_Role", "\"Role\" IN ('USER', 'ASSISTANT', 'SYSTEM')");

                            t.HasCheckConstraint("CK_Message_Status", "\"Status\" IN ('completed', 'generating', 'cancelled', 'failed')");
                        });
                });

            modelBuilder.Entity("Spilton.Api.Data.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7d34e4d3-0b27-4612-a3ed-563aa5c22ae7"),
                            Name = "User"
                        });
                });

            modelBuilder.Entity("Spilton.Api.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Spilton.Api.Documents.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("integer");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmbeddingModel")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Error")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("PageCount")
                        .HasColumnType("integer");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("SpaceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("StoredName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SpaceId");

                    b.HasIndex("StoredName")
                        .IsUnique();

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("Documents", t =>
                        {
                            t.HasCheckConstraint("CK_Document_Status", "\"Status\" IN ('UPLOADED','PROCESSING','READY','FAILED','DELETING')");
                        });
                });

            modelBuilder.Entity("Spilton.Api.Documents.DocumentChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(6000)
                        .HasColumnType("character varying(6000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(384)");

                    b.Property<int?>("PageNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Section")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TokenCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "ChunkIndex")
                        .IsUnique();

                    b.ToTable("DocumentChunks");
                });

            modelBuilder.Entity("Spilton.Api.Preparation.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Exams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5203a36e-3f14-28c5-3cf5-dbfb9e8dbdc7"),
                            Family = "SSC",
                            Name = "SSC CGL"
                        },
                        new
                        {
                            Id = new Guid("c7eb30df-82ba-b681-16bc-d42281260567"),
                            Family = "SSC",
                            Name = "SSC CHSL"
                        },
                        new
                        {
                            Id = new Guid("67a09dd0-b1f9-3056-07f7-38bfce69de44"),
                            Family = "RRB",
                            Name = "RRB NTPC"
                        },
                        new
                        {
                            Id = new Guid("bf3e0171-deb0-4a7a-6220-a554625c1e20"),
                            Family = "Banking",
                            Name = "Banking Preparation"
                        },
                        new
                        {
                            Id = new Guid("0838d026-1d31-25ad-921b-4f88b7fd16fc"),
                            Family = "APPSC",
                            Name = "APPSC Preparation"
                        },
                        new
                        {
                            Id = new Guid("25b6217a-7b02-4fc6-13a6-3a9b3bdc187a"),
                            Family = "UPSC",
                            Name = "UPSC Preparation"
                        });
                });

            modelBuilder.Entity("Spilton.Api.Preparation.ExamStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("ExamStages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4b4b85c5-7efc-17c3-ea31-575f3fde09c0"),
                            ExamId = new Guid("5203a36e-3f14-28c5-3cf5-dbfb9e8dbdc7"),
                            Name = "Tier 1"
                        },
                        new
                        {
                            Id = new Guid("6eaea10a-e489-75bd-be06-38b2bdd1c22e"),
                            ExamId = new Guid("5203a36e-3f14-28c5-3cf5-dbfb9e8dbdc7"),
                            Name = "Tier 2"
                        },
                        new
                        {
                            Id = new Guid("799d3509-b2d3-1051-8a21-e8ec1ac8dbf4"),
                            ExamId = new Guid("c7eb30df-82ba-b681-16bc-d42281260567"),
                            Name = "Tier 1"
                        },
                        new
                        {
                            Id = new Guid("363fe794-8cd0-f203-f40c-95247fef1ecc"),
                            ExamId = new Guid("c7eb30df-82ba-b681-16bc-d42281260567"),
                            Name = "Tier 2"
                        },
                        new
                        {
                            Id = new Guid("05887fde-7a0e-b43f-d508-f1cfa7bf75d1"),
                            ExamId = new Guid("67a09dd0-b1f9-3056-07f7-38bfce69de44"),
                            Name = "General preparation"
                        },
                        new
                        {
                            Id = new Guid("6e360767-ff22-4509-7328-03511808a4ab"),
                            ExamId = new Guid("bf3e0171-deb0-4a7a-6220-a554625c1e20"),
                            Name = "General preparation"
                        },
                        new
                        {
                            Id = new Guid("19ca8ca9-d21f-575f-7af9-3310e764aa70"),
                            ExamId = new Guid("0838d026-1d31-25ad-921b-4f88b7fd16fc"),
                            Name = "General preparation"
                        },
                        new
                        {
                            Id = new Guid("5d62f58a-58ac-9e20-37c8-5ee91b6928c4"),
                            ExamId = new Guid("25b6217a-7b02-4fc6-13a6-3a9b3bdc187a"),
                            Name = "General preparation"
                        });
                });

            modelBuilder.Entity("Spilton.Api.Preparation.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SpaceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SpaceId");

                    b.HasIndex("UserId", "SpaceId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("Spilton.Api.Preparation.Memory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("SpaceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SpaceId");

                    b.HasIndex("UserId", "SpaceId");

                    b.ToTable("Memories");
                });

            modelBuilder.Entity("Spilton.Api.Preparation.Space", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsArchived");

                    b.ToTable("Spaces");
                });

            modelBuilder.Entity("Spilton.Api.Preparation.StudyPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Days")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SpaceId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SpaceId");

                    b.HasIndex("UserId", "SpaceId");

                    b.ToTable("StudyPlans");
                });

            modelBuilder.Entity("Spilton.Api.Preparation.StudyPlanItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Minutes")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("StudyPlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.HasIndex("StudyPlanId", "Date");

                    b.ToTable("StudyPlanItems");
                });

            modelBuilder.Entity("Spilton.Api.Preparation.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExamStageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ExamStageId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a98cd19f-ab5f-c3a3-bfaa-b5bf97ad8026"),
                            ExamStageId = new Guid("4b4b85c5-7efc-17c3-ea31-575f3fde09c0"),
                            Name = "Quantitative Aptitude"
                        },
                        new
                        {
                            Id = new Guid("4a5581f2-39c2-c9c7-50ad-954a957f1b07"),
                            ExamStageId = new Guid("4b4b85c5-7efc-17c3-ea31-575f3fde09c0"),
                            Name = "Reasoning"
                        },
                        new
                        {
                            Id = new Guid("898eb630-9c17-9ee7-c375-739dc4c14ead"),
                            ExamStageId = new Guid("4b4b85c5-7efc-17c3-ea31-575f3fde09c0"),
                            Name = "English"
                        },
                        new
                        {
                            Id = new Guid("899ad66e-cb98-e49a-6994-05c201d848fa"),
                            ExamStageId = new Guid("4b4b85c5-7efc-17c3-ea31-575f3fde09c0"),
                            Name = "General Awareness"
                        },
                        new
                        {
                            Id = new Guid("a0fe7782-735b-c64b-5ee0-ef642bd4b412"),
                            ExamStageId = new Guid("6eaea10a-e489-75bd-be06-38b2bdd1c22e"),
                            Name = "Quantitative Aptitude"
                        },
                        new
                        {
                            Id = new Guid("2b9c687b-8c73-8bec-723f-33d1b2ed4c49"),
                            ExamStageId = new Guid("6eaea10a-e489-75bd-be06-38b2bdd1c22e"),
                            Name = "Reasoning"
                        },
                        new
                        {
                            Id = new Guid("52732bab-625e-b767-0dea-6f39a2f403cb"),
                            ExamStageId = new Guid("6eaea10a-e489-75bd-be06-38b2bdd1c22e"),
                            Name = "English"
                        },
                        new
                        {
                            Id = new Guid("21adc355-8586-e349-28e8-3a4492e3c8a6"),
                            ExamStageId = new Guid("6eaea10a-e489-75bd-be06-38b2bdd1c22e"),
                            Name = "General Awareness"
                        },
                        new
                        {
                            Id = new Guid("c48473f0-e6ac-dd2b-2aca-5c9ed9ca886b"),
                            ExamStageId = new Guid("799d3509-b2d3-1051-8a21-e8ec1ac8dbf4"),
                            Name = "Quantitative Aptitude"
                        },
                        new
                        {
                            Id = new Guid("6e95c6b1-5db5-855a-cc9b-5be0a1bcf838"),
                            ExamStageId = new Guid("799d3509-b2d3-1051-8a21-e8ec1ac8dbf4"),
                            Name = "Reasoning"
                        },
                        new
                        {
                            Id = new Guid("90347abb-8fcd-7d22-748c-00c8bcf30b49"),
                            ExamStageId = new Guid("799d3509-b2d3-1051-8a21-e8ec1ac8dbf4"),
                            Name = "English"
                        },
                        new
                        {
                            Id = new Guid("2dcd5d84-67cb-7ae2-4f7e-7fb7699ae2df"),
                            ExamStageId = new Guid("799d3509-b2d3-1051-8a21-e8ec1ac8dbf4"),
                            Name = "General Awareness"
                        },
                        new
                        {
                            Id = new Guid("6c42f073-e167-13ea-1e64-4667f30548d2"),
                            ExamStageId = new Guid("363fe794-8cd0-f203-f40c-95247fef1ecc"),
                            Name = "Quantitative Aptitude"
                        },
                        new
                        {
                            Id = new Guid("b1979e05-7e07-b2f8-d3f8-821dbb1ce6dd"),
                            ExamStageId = new Guid("363fe794-8cd0-f203-f40c-95247fef1ecc"),
                            Name = "Reasoning"
                        },
                        new
                        {
                            Id = new Guid("1cf1914a-70a9-0732-71a9-2658384fa516"),
                            ExamStageId = new Guid("363fe794-8cd0-f203-f40c-95247fef1ecc"),
                            Name = "English"
                        },
                        new
                        {
                            Id = new Guid("08a8470e-bb21-548e-0a08-60a5f3bff9df"),
                            ExamStageId = new Guid("363fe794-8cd0-f203-f40c-95247fef1ecc"),
                            Name = "General Awareness"
                        },
                        new
                        {
                            Id = new Guid("02db2b9a-c84b-5ce1-0f3c-68969f7e554c"),
                            ExamStageId = new Guid("05887fde-7a0e-b43f-d508-f1cfa7bf75d1"),
                            Name = "Quantitative Aptitude"
                        },
                        new
                        {
                            Id = new Guid("e0368c2d-0969-a6d1-09bd-8e27f2e79993"),
                            ExamStageId = new Guid("05887fde-7a0e-b43f-d508-f1cfa7bf75d1"),
                            Name = "Reasoning"
                        },
                        new
                        {
                            Id = new Guid("2f7d3cf3-0488-9ba8-c202-25354dcddf64"),
                            ExamStageId = new Guid("05887fde-7a0e-b43f-d508-f1cfa7bf75d1"),
                            Name = "English"
                        },
                        new
                        {
                            Id = new Guid("12e911ad-fe68-6d34-81aa-2a3e423479fe"),
                            ExamStageId = new Guid("05887fde-7a0e-b43f-d508-f1cfa7bf75d1"),
                            Name = "General Awareness"
                        },
                        new
                        {
                            Id = new Guid("af68f49f-904d-04cc-ab49-e20ae7b87985"),
                            ExamStageId = new Guid("6e360767-ff22-4509-7328-03511808a4ab"),
                            Name = "Quantitative Aptitude"
                        },
                        new
                        {
                            Id = new Guid("2aded84d-55ba-7fe6-5912-6eb2e4108adb"),
                            ExamStageId = new Guid("6e360767-ff22-4509-7328-03511808a4ab"),
                            Name = "Reasoning"
                        },
                        new
                        {
                            Id = new Guid("593ab663-779a-cd4b-e7c3-9b0e29a0aea9"),
                            ExamStageId = new Guid("6e360767-ff22-4509-7328-03511808a4ab"),
                            Name = "English"
                        },
                        new
                        {
                            Id = new Guid("ab42a4f6-2ca3-1387-f605-7541d3bdc964"),
                            ExamStageId = new Guid("6e360767-ff22-4509-7328-03511808a4ab"),
                            Name = "General Awareness"
                        },
                        new
                        {
                            Id = new Guid("ef6d15a8-abfc-4a2b-ac8d-5033319bc397"),
                            ExamStageId = new Guid("19ca8ca9-d21f-575f-7af9-3310e764aa70"),
                            Name = "Quantitative Aptitude"
                        },
                        new
                        {
                            Id = new Guid("75bb5701-e8eb-3fba-15ea-f4d403ccde0e"),
                            ExamStageId = new Guid("19ca8ca9-d21f-575f-7af9-3310e764aa70"),
                            Name = "Reasoning"
                        },
                        new
                        {
                            Id = new Guid("87b72a5b-9923-e0a8-542c-95024f4d41a0"),
                            ExamStageId = new Guid("19ca8ca9-d21f-575f-7af9-3310e764aa70"),
                            Name = "English"
                        },
                        new
                        {
                            Id = new Guid("3d7d71ba-9120-b239-d696-715b35ee5535"),
                            ExamStageId = new Guid("19ca8ca9-d21f-575f-7af9-3310e764aa70"),
                            Name = "General Awareness"
                        },
                        new
                        {
                            Id = new Guid("327fe777-c46f-0930-3f8f-744612e374b0"),
                            ExamStageId = new Guid("5d62f58a-58ac-9e20-37c8-5ee91b6928c4"),
                            Name = "Quantitative Aptitude"
                        },
                        new
                        {
                            Id = new Guid("3ae9430f-30bb-52a1-643c-f18ee6522b95"),
                            ExamStageId = new Guid("5d62f58a-58ac-9e20-37c8-5ee91b6928c4"),
                            Name = "Reasoning"
                        },
                        new
                        {
                            Id = new Guid("1f274bfd-5c4d-b4fe-522d-2fc070566c42"),
                            ExamStageId = new Guid("5d62f58a-58ac-9e20-37c8-5ee91b6928c4"),
                            Name = "English"
                        },
                        new
                        {
                            Id = new Guid("95c19115-0ff0-2d83-7ea8-8fa8ec49d3bd"),
                            ExamStageId = new Guid("5d62f58a-58ac-9e20-37c8-5ee91b6928c4"),
                            Name = "General Awareness"
                        });
                });

            modelBuilder.Entity("Spilton.Api.Preparation.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9754bfa5-5e7a-b81c-8161-3fc2da4e288f"),
                            Name = "Percentage",
                            SubjectId = new Guid("a98cd19f-ab5f-c3a3-bfaa-b5bf97ad8026")
                        },
                        new
                        {
                            Id = new Guid("f1e66e7e-a06d-67b9-8d94-d01d673eb98e"),
                            Name = "Profit and Loss",
                            SubjectId = new Guid("a98cd19f-ab5f-c3a3-bfaa-b5bf97ad8026")
                        },
                        new
                        {
                            Id = new Guid("eb4a7173-cf71-5602-fad5-b7622551d3a0"),
                            Name = "Geometry",
                            SubjectId = new Guid("a98cd19f-ab5f-c3a3-bfaa-b5bf97ad8026")
                        },
                        new
                        {
                            Id = new Guid("bf1955d0-11b7-df71-9ed2-e2cfed10d136"),
                            Name = "Coding-Decoding",
                            SubjectId = new Guid("4a5581f2-39c2-c9c7-50ad-954a957f1b07")
                        },
                        new
                        {
                            Id = new Guid("8d7b8cc9-3012-3b52-d363-7a56040366ba"),
                            Name = "Series",
                            SubjectId = new Guid("4a5581f2-39c2-c9c7-50ad-954a957f1b07")
                        },
                        new
                        {
                            Id = new Guid("2ebfdf1f-2971-2d0f-f951-00063170d10e"),
                            Name = "Logical Reasoning",
                            SubjectId = new Guid("4a5581f2-39c2-c9c7-50ad-954a957f1b07")
                        },
                        new
                        {
                            Id = new Guid("5a91af83-a3c5-f4c8-83d8-dd35fa977f77"),
                            Name = "Error Detection",
                            SubjectId = new Guid("898eb630-9c17-9ee7-c375-739dc4c14ead")
                        },
                        new
                        {
                            Id = new Guid("c3f6082b-a2bf-85d7-5d1e-868dcc2da9c1"),
                            Name = "Reading Comprehension",
                            SubjectId = new Guid("898eb630-9c17-9ee7-c375-739dc4c14ead")
                        },
                        new
                        {
                            Id = new Guid("ce48134c-a931-4849-7d0e-29e74f20eb32"),
                            Name = "Vocabulary",
                            SubjectId = new Guid("898eb630-9c17-9ee7-c375-739dc4c14ead")
                        },
                        new
                        {
                            Id = new Guid("2ee79a5c-1817-7974-b10f-9556ddf79938"),
                            Name = "Static GK",
                            SubjectId = new Guid("899ad66e-cb98-e49a-6994-05c201d848fa")
                        },
                        new
                        {
                            Id = new Guid("0c88667f-08a5-ccaa-9eb7-04782a94abee"),
                            Name = "History",
                            SubjectId = new Guid("899ad66e-cb98-e49a-6994-05c201d848fa")
                        },
                        new
                        {
                            Id = new Guid("5d3e3c61-4455-b80c-9ec9-2eab28bb721b"),
                            Name = "Geography",
                            SubjectId = new Guid("899ad66e-cb98-e49a-6994-05c201d848fa")
                        },
                        new
                        {
                            Id = new Guid("fcc8ae34-0921-9c15-99c6-193b772710a2"),
                            Name = "Percentage",
                            SubjectId = new Guid("a0fe7782-735b-c64b-5ee0-ef642bd4b412")
                        },
                        new
                        {
                            Id = new Guid("8ebca2dc-dd8e-a08a-b354-50152075dbbf"),
                            Name = "Profit and Loss",
                            SubjectId = new Guid("a0fe7782-735b-c64b-5ee0-ef642bd4b412")
                        },
                        new
                        {
                            Id = new Guid("1e6274aa-ed80-cc26-e2d4-6d318310d57d"),
                            Name = "Geometry",
                            SubjectId = new Guid("a0fe7782-735b-c64b-5ee0-ef642bd4b412")
                        },
                        new
                        {
                            Id = new Guid("a9192b7f-cfeb-7435-d324-0da87d599e10"),
                            Name = "Coding-Decoding",
                            SubjectId = new Guid("2b9c687b-8c73-8bec-723f-33d1b2ed4c49")
                        },
                        new
                        {
                            Id = new Guid("5965fef8-8a16-72a9-e6c5-39c5f374de40"),
                            Name = "Series",
                            SubjectId = new Guid("2b9c687b-8c73-8bec-723f-33d1b2ed4c49")
                        },
                        new
                        {
                            Id = new Guid("01f4eab0-a154-61cd-f5fc-56eef6fdbe13"),
                            Name = "Logical Reasoning",
                            SubjectId = new Guid("2b9c687b-8c73-8bec-723f-33d1b2ed4c49")
                        },
                        new
                        {
                            Id = new Guid("9b817e8d-9aea-54ec-61c7-445a7e15669e"),
                            Name = "Error Detection",
                            SubjectId = new Guid("52732bab-625e-b767-0dea-6f39a2f403cb")
                        },
                        new
                        {
                            Id = new Guid("4673749d-37e7-bac2-96cd-a1d61dc9ab3f"),
                            Name = "Reading Comprehension",
                            SubjectId = new Guid("52732bab-625e-b767-0dea-6f39a2f403cb")
                        },
                        new
                        {
                            Id = new Guid("06b1fe07-1bf1-b969-ccbc-d50f8dc66fec"),
                            Name = "Vocabulary",
                            SubjectId = new Guid("52732bab-625e-b767-0dea-6f39a2f403cb")
                        },
                        new
                        {
                            Id = new Guid("89162032-759c-8685-6da6-533cef1121c2"),
                            Name = "Static GK",
                            SubjectId = new Guid("21adc355-8586-e349-28e8-3a4492e3c8a6")
                        },
                        new
                        {
                            Id = new Guid("af538c04-c2fc-7ec6-5f6a-4f33b09f8334"),
                            Name = "History",
                            SubjectId = new Guid("21adc355-8586-e349-28e8-3a4492e3c8a6")
                        },
                        new
                        {
                            Id = new Guid("93706aea-8c53-0363-c36f-8d9ae42c3f16"),
                            Name = "Geography",
                            SubjectId = new Guid("21adc355-8586-e349-28e8-3a4492e3c8a6")
                        },
                        new
                        {
                            Id = new Guid("eff265cf-0259-ff43-e16f-aeb8b62a5c85"),
                            Name = "Percentage",
                            SubjectId = new Guid("c48473f0-e6ac-dd2b-2aca-5c9ed9ca886b")
                        },
                        new
                        {
                            Id = new Guid("334d3aaa-6503-7f88-3b06-a9a9294bd734"),
                            Name = "Profit and Loss",
                            SubjectId = new Guid("c48473f0-e6ac-dd2b-2aca-5c9ed9ca886b")
                        },
                        new
                        {
                            Id = new Guid("39e33197-d66c-4dee-aac1-c712efff430b"),
                            Name = "Geometry",
                            SubjectId = new Guid("c48473f0-e6ac-dd2b-2aca-5c9ed9ca886b")
                        },
                        new
                        {
                            Id = new Guid("92d9544d-5356-a90f-b122-277fa9df7502"),
                            Name = "Coding-Decoding",
                            SubjectId = new Guid("6e95c6b1-5db5-855a-cc9b-5be0a1bcf838")
                        },
                        new
                        {
                            Id = new Guid("a508f4cf-0d9c-7629-2aea-da74deb105aa"),
                            Name = "Series",
                            SubjectId = new Guid("6e95c6b1-5db5-855a-cc9b-5be0a1bcf838")
                        },
                        new
                        {
                            Id = new Guid("f7717f83-aa0a-4e8c-eb0a-8d601ed47c1a"),
                            Name = "Logical Reasoning",
                            SubjectId = new Guid("6e95c6b1-5db5-855a-cc9b-5be0a1bcf838")
                        },
                        new
                        {
                            Id = new Guid("94626a7c-8a7c-7052-e24e-6168a14b619a"),
                            Name = "Error Detection",
                            SubjectId = new Guid("90347abb-8fcd-7d22-748c-00c8bcf30b49")
                        },
                        new
                        {
                            Id = new Guid("c1739f76-fe2f-9a76-e216-97b9684a8096"),
                            Name = "Reading Comprehension",
                            SubjectId = new Guid("90347abb-8fcd-7d22-748c-00c8bcf30b49")
                        },
                        new
                        {
                            Id = new Guid("f76da6cd-e43f-d734-9aa7-ab93db200cd5"),
                            Name = "Vocabulary",
                            SubjectId = new Guid("90347abb-8fcd-7d22-748c-00c8bcf30b49")
                        },
                        new
                        {
                            Id = new Guid("6c04f604-b96a-837e-8464-c1baa43feb1e"),
                            Name = "Static GK",
                            SubjectId = new Guid("2dcd5d84-67cb-7ae2-4f7e-7fb7699ae2df")
                        },
                        new
                        {
                            Id = new Guid("20d8f7f2-f489-3229-dc4e-742370a8acf0"),
                            Name = "History",
                            SubjectId = new Guid("2dcd5d84-67cb-7ae2-4f7e-7fb7699ae2df")
                        },
                        new
                        {
                            Id = new Guid("22a8fbdb-66b6-8f15-d6f3-757c30fb9b0e"),
                            Name = "Geography",
                            SubjectId = new Guid("2dcd5d84-67cb-7ae2-4f7e-7fb7699ae2df")
                        },
                        new
                        {
                            Id = new Guid("a013f134-8288-247f-8e55-cd8e6137b559"),
                            Name = "Percentage",
                            SubjectId = new Guid("6c42f073-e167-13ea-1e64-4667f30548d2")
                        },
                        new
                        {
                            Id = new Guid("3d47e2f4-9c72-e951-443e-a7221f98238d"),
                            Name = "Profit and Loss",
                            SubjectId = new Guid("6c42f073-e167-13ea-1e64-4667f30548d2")
                        },
                        new
                        {
                            Id = new Guid("e97a927c-4d5a-64a6-dbeb-6ed70658b969"),
                            Name = "Geometry",
                            SubjectId = new Guid("6c42f073-e167-13ea-1e64-4667f30548d2")
                        },
                        new
                        {
                            Id = new Guid("66128a1f-3059-b75e-f522-f128417cf043"),
                            Name = "Coding-Decoding",
                            SubjectId = new Guid("b1979e05-7e07-b2f8-d3f8-821dbb1ce6dd")
                        },
                        new
                        {
                            Id = new Guid("b9ee7ef5-1fa2-4b96-1e7b-b40906edc356"),
                            Name = "Series",
                            SubjectId = new Guid("b1979e05-7e07-b2f8-d3f8-821dbb1ce6dd")
                        },
                        new
                        {
                            Id = new Guid("839252bf-9f0c-ba1f-abee-2f8a70ca6861"),
                            Name = "Logical Reasoning",
                            SubjectId = new Guid("b1979e05-7e07-b2f8-d3f8-821dbb1ce6dd")
                        },
                        new
                        {
                            Id = new Guid("006afb85-c37d-6d54-1243-585e54319538"),
                            Name = "Error Detection",
                            SubjectId = new Guid("1cf1914a-70a9-0732-71a9-2658384fa516")
                        },
                        new
                        {
                            Id = new Guid("439b6a39-8457-bc3d-c730-5098be909350"),
                            Name = "Reading Comprehension",
                            SubjectId = new Guid("1cf1914a-70a9-0732-71a9-2658384fa516")
                        },
                        new
                        {
                            Id = new Guid("839d98a7-deef-5095-a0f9-25e41cc8ac1f"),
                            Name = "Vocabulary",
                            SubjectId = new Guid("1cf1914a-70a9-0732-71a9-2658384fa516")
                        },
                        new
                        {
                            Id = new Guid("59edbd10-66a3-bc0e-e02a-ac85e2b9d278"),
                            Name = "Static GK",
                            SubjectId = new Guid("08a8470e-bb21-548e-0a08-60a5f3bff9df")
                        },
                        new
                        {
                            Id = new Guid("2c551512-d791-2479-27dc-763d619598d3"),
                            Name = "History",
                            SubjectId = new Guid("08a8470e-bb21-548e-0a08-60a5f3bff9df")
                        },
                        new
                        {
                            Id = new Guid("14107032-8fb9-162f-55a5-50fe0e2d9589"),
                            Name = "Geography",
                            SubjectId = new Guid("08a8470e-bb21-548e-0a08-60a5f3bff9df")
                        },
                        new
                        {
                            Id = new Guid("df0d7024-e61d-ff8d-5d42-f1f9afa07246"),
                            Name = "Percentage",
                            SubjectId = new Guid("02db2b9a-c84b-5ce1-0f3c-68969f7e554c")
                        },
                        new
                        {
                            Id = new Guid("e2d7b0fa-03f3-b73f-b386-e105b84d64c2"),
                            Name = "Profit and Loss",
                            SubjectId = new Guid("02db2b9a-c84b-5ce1-0f3c-68969f7e554c")
                        },
                        new
                        {
                            Id = new Guid("ace98aff-d3d3-2d59-d406-090d6720333d"),
                            Name = "Geometry",
                            SubjectId = new Guid("02db2b9a-c84b-5ce1-0f3c-68969f7e554c")
                        },
                        new
                        {
                            Id = new Guid("17845109-183d-1709-ce68-934b7b9e3685"),
                            Name = "Coding-Decoding",
                            SubjectId = new Guid("e0368c2d-0969-a6d1-09bd-8e27f2e79993")
                        },
                        new
                        {
                            Id = new Guid("ca48c4e3-fb3d-7413-ad65-a20dd325a4f4"),
                            Name = "Series",
                            SubjectId = new Guid("e0368c2d-0969-a6d1-09bd-8e27f2e79993")
                        },
                        new
                        {
                            Id = new Guid("ad98d2ef-ad94-2e92-5543-c4eb6bd96646"),
                            Name = "Logical Reasoning",
                            SubjectId = new Guid("e0368c2d-0969-a6d1-09bd-8e27f2e79993")
                        },
                        new
                        {
                            Id = new Guid("286f2db0-b99d-2617-0702-69ee0d3540dc"),
                            Name = "Error Detection",
                            SubjectId = new Guid("2f7d3cf3-0488-9ba8-c202-25354dcddf64")
                        },
                        new
                        {
                            Id = new Guid("2ec656d6-0d74-15d7-af98-429f1e323386"),
                            Name = "Reading Comprehension",
                            SubjectId = new Guid("2f7d3cf3-0488-9ba8-c202-25354dcddf64")
                        },
                        new
                        {
                            Id = new Guid("6e1d1084-dce5-7b94-12ab-3438861d8056"),
                            Name = "Vocabulary",
                            SubjectId = new Guid("2f7d3cf3-0488-9ba8-c202-25354dcddf64")
                        },
                        new
                        {
                            Id = new Guid("2a8a2294-1840-5693-82c1-25fc4adefba5"),
                            Name = "Static GK",
                            SubjectId = new Guid("12e911ad-fe68-6d34-81aa-2a3e423479fe")
                        },
                        new
                        {
                            Id = new Guid("69afcae3-e269-781d-d72c-6e4330e17b35"),
                            Name = "History",
                            SubjectId = new Guid("12e911ad-fe68-6d34-81aa-2a3e423479fe")
                        },
                        new
                        {
                            Id = new Guid("7858feb1-4d59-0324-7735-642cbfa925d8"),
                            Name = "Geography",
                            SubjectId = new Guid("12e911ad-fe68-6d34-81aa-2a3e423479fe")
                        },
                        new
                        {
                            Id = new Guid("e2f82265-1818-2113-593a-80a45fe4c8f9"),
                            Name = "Percentage",
                            SubjectId = new Guid("af68f49f-904d-04cc-ab49-e20ae7b87985")
                        },
                        new
                        {
                            Id = new Guid("fa2e958e-86a0-2eb7-9943-b3eeaacf03a6"),
                            Name = "Profit and Loss",
                            SubjectId = new Guid("af68f49f-904d-04cc-ab49-e20ae7b87985")
                        },
                        new
                        {
                            Id = new Guid("5430fd48-a166-89f3-5111-39a8e6c491c3"),
                            Name = "Geometry",
                            SubjectId = new Guid("af68f49f-904d-04cc-ab49-e20ae7b87985")
                        },
                        new
                        {
                            Id = new Guid("52662e2e-85b0-8144-a50b-4da97b33af29"),
                            Name = "Coding-Decoding",
                            SubjectId = new Guid("2aded84d-55ba-7fe6-5912-6eb2e4108adb")
                        },
                        new
                        {
                            Id = new Guid("cb3a3ad6-82e1-e43e-6bdd-6cb1c5214437"),
                            Name = "Series",
                            SubjectId = new Guid("2aded84d-55ba-7fe6-5912-6eb2e4108adb")
                        },
                        new
                        {
                            Id = new Guid("73b138b6-019d-6d5b-d67e-3d1aef783759"),
                            Name = "Logical Reasoning",
                            SubjectId = new Guid("2aded84d-55ba-7fe6-5912-6eb2e4108adb")
                        },
                        new
                        {
                            Id = new Guid("5b475785-58a5-2cd6-24a4-83f0e4e450cc"),
                            Name = "Error Detection",
                            SubjectId = new Guid("593ab663-779a-cd4b-e7c3-9b0e29a0aea9")
                        },
                        new
                        {
                            Id = new Guid("a97fed4c-a034-c80c-fae0-a9939f343df3"),
                            Name = "Reading Comprehension",
                            SubjectId = new Guid("593ab663-779a-cd4b-e7c3-9b0e29a0aea9")
                        },
                        new
                        {
                            Id = new Guid("6483005c-f65a-318d-5a89-ca0bc7e4729d"),
                            Name = "Vocabulary",
                            SubjectId = new Guid("593ab663-779a-cd4b-e7c3-9b0e29a0aea9")
                        },
                        new
                        {
                            Id = new Guid("27b89e12-3f6b-64a4-0250-e8d8042ddd95"),
                            Name = "Static GK",
                            SubjectId = new Guid("ab42a4f6-2ca3-1387-f605-7541d3bdc964")
                        },
                        new
                        {
                            Id = new Guid("4dee5ee3-c624-7f52-61f9-591ee98d7b2a"),
                            Name = "History",
                            SubjectId = new Guid("ab42a4f6-2ca3-1387-f605-7541d3bdc964")
                        },
                        new
                        {
                            Id = new Guid("72ce00f0-db1e-2474-089f-c736873706a9"),
                            Name = "Geography",
                            SubjectId = new Guid("ab42a4f6-2ca3-1387-f605-7541d3bdc964")
                        },
                        new
                        {
                            Id = new Guid("84f9036a-6937-6926-5cd9-fa173c8f78cf"),
                            Name = "Percentage",
                            SubjectId = new Guid("ef6d15a8-abfc-4a2b-ac8d-5033319bc397")
                        },
                        new
                        {
                            Id = new Guid("b9185fac-59a7-7a42-fb9c-e744afae7bcc"),
                            Name = "Profit and Loss",
                            SubjectId = new Guid("ef6d15a8-abfc-4a2b-ac8d-5033319bc397")
                        },
                        new
                        {
                            Id = new Guid("094c94f6-10fb-987d-5def-9fd55898cccd"),
                            Name = "Geometry",
                            SubjectId = new Guid("ef6d15a8-abfc-4a2b-ac8d-5033319bc397")
                        },
                        new
                        {
                            Id = new Guid("5832a310-92ff-b5c6-bb5d-7309be073ca7"),
                            Name = "Coding-Decoding",
                            SubjectId = new Guid("75bb5701-e8eb-3fba-15ea-f4d403ccde0e")
                        },
                        new
                        {
                            Id = new Guid("e77f73c8-94ef-bb10-0a63-efc740d2cac5"),
                            Name = "Series",
                            SubjectId = new Guid("75bb5701-e8eb-3fba-15ea-f4d403ccde0e")
                        },
                        new
                        {
                            Id = new Guid("464915d3-d5e7-b39e-b10d-74e8d66fb544"),
                            Name = "Logical Reasoning",
                            SubjectId = new Guid("75bb5701-e8eb-3fba-15ea-f4d403ccde0e")
                        },
                        new
                        {
                            Id = new Guid("698bfa28-befc-6378-2794-69124e2dde80"),
                            Name = "Error Detection",
                            SubjectId = new Guid("87b72a5b-9923-e0a8-542c-95024f4d41a0")
                        },
                        new
                        {
                            Id = new Guid("36b5ba94-5236-85de-f492-9e986fff2d5a"),
                            Name = "Reading Comprehension",
                            SubjectId = new Guid("87b72a5b-9923-e0a8-542c-95024f4d41a0")
                        },
                        new
                        {
                            Id = new Guid("78363a1d-bab5-44c7-3b11-1cce097dc5b5"),
                            Name = "Vocabulary",
                            SubjectId = new Guid("87b72a5b-9923-e0a8-542c-95024f4d41a0")
                        },
                        new
                        {
                            Id = new Guid("de1722c8-8d74-8ebc-37bc-fcf407c468b4"),
                            Name = "Static GK",
                            SubjectId = new Guid("3d7d71ba-9120-b239-d696-715b35ee5535")
                        },
                        new
                        {
                            Id = new Guid("0e00b532-de5f-e958-fc3c-bff990da3ad7"),
                            Name = "History",
                            SubjectId = new Guid("3d7d71ba-9120-b239-d696-715b35ee5535")
                        },
                        new
                        {
                            Id = new Guid("a8c35efe-1c10-552d-3549-27fd2de16f2d"),
                            Name = "Geography",
                            SubjectId = new Guid("3d7d71ba-9120-b239-d696-715b35ee5535")
                        },
                        new
                        {
                            Id = new Guid("0520243f-cc6e-cb5c-edc4-bce6d0c03e19"),
                            Name = "Percentage",
                            SubjectId = new Guid("327fe777-c46f-0930-3f8f-744612e374b0")
                        },
                        new
                        {
                            Id = new Guid("c515467a-9cd4-244b-ef48-e92f9c4d1f2a"),
                            Name = "Profit and Loss",
                            SubjectId = new Guid("327fe777-c46f-0930-3f8f-744612e374b0")
                        },
                        new
                        {
                            Id = new Guid("842f6749-85f2-0e2b-ce48-a0b6e5ac1909"),
                            Name = "Geometry",
                            SubjectId = new Guid("327fe777-c46f-0930-3f8f-744612e374b0")
                        },
                        new
                        {
                            Id = new Guid("e8be4456-b4bd-9d6f-fad1-266957f6418d"),
                            Name = "Coding-Decoding",
                            SubjectId = new Guid("3ae9430f-30bb-52a1-643c-f18ee6522b95")
                        },
                        new
                        {
                            Id = new Guid("6c2e7c8d-0f31-ec8d-aaba-5b50303c8ef7"),
                            Name = "Series",
                            SubjectId = new Guid("3ae9430f-30bb-52a1-643c-f18ee6522b95")
                        },
                        new
                        {
                            Id = new Guid("dbde005b-64cb-d165-6712-d79c60505484"),
                            Name = "Logical Reasoning",
                            SubjectId = new Guid("3ae9430f-30bb-52a1-643c-f18ee6522b95")
                        },
                        new
                        {
                            Id = new Guid("20012ca9-ebad-57d4-e71e-599966845b08"),
                            Name = "Error Detection",
                            SubjectId = new Guid("1f274bfd-5c4d-b4fe-522d-2fc070566c42")
                        },
                        new
                        {
                            Id = new Guid("7d54ed12-b21b-93d0-8326-9a125f828ed5"),
                            Name = "Reading Comprehension",
                            SubjectId = new Guid("1f274bfd-5c4d-b4fe-522d-2fc070566c42")
                        },
                        new
                        {
                            Id = new Guid("f32e366b-7222-c6d4-03cc-993f440f683b"),
                            Name = "Vocabulary",
                            SubjectId = new Guid("1f274bfd-5c4d-b4fe-522d-2fc070566c42")
                        },
                        new
                        {
                            Id = new Guid("940f66d7-879d-c1f3-6160-58bddcd006d8"),
                            Name = "Static GK",
                            SubjectId = new Guid("95c19115-0ff0-2d83-7ea8-8fa8ec49d3bd")
                        },
                        new
                        {
                            Id = new Guid("2e357b40-0f2f-a20c-731a-9306154b8501"),
                            Name = "History",
                            SubjectId = new Guid("95c19115-0ff0-2d83-7ea8-8fa8ec49d3bd")
                        },
                        new
                        {
                            Id = new Guid("3dfa2226-b829-39a3-7e60-74f7813318f5"),
                            Name = "Geography",
                            SubjectId = new Guid("95c19115-0ff0-2d83-7ea8-8fa8ec49d3bd")
                        });
                });

            modelBuilder.Entity("Spilton.Api.Preparation.UserExamProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DailyMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("ExamStageId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ExpectedExamDate")
                        .HasColumnType("date");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("SpaceId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<int?>("TargetScore")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExamStageId");

                    b.HasIndex("SpaceId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("\"SpaceId\" IS NULL");

                    b.HasIndex("UserId", "SpaceId")
                        .IsUnique();

                    b.ToTable("UserExamProfiles");
                });

            modelBuilder.Entity("Spilton.Api.Preparation.UserTopicProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ConfidenceScore")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastPracticedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("QuestionsAttempted")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionsCorrect")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserExamProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.HasIndex("UserExamProfileId", "TopicId")
                        .IsUnique();

                    b.ToTable("UserTopicProgress", t =>
                        {
                            t.HasCheckConstraint("CK_Progress_Counts", "\"QuestionsAttempted\" >= 0 AND \"QuestionsCorrect\" >= 0 AND \"QuestionsCorrect\" <= \"QuestionsAttempted\"");
                        });
                });

            modelBuilder.Entity("UserRoles", b =>
                {
                    b.Property<Guid>("RolesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Spilton.Api.Chat.Conversation", b =>
                {
                    b.HasOne("Spilton.Api.Preparation.Space", "Space")
                        .WithMany()
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Spilton.Api.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Space");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Spilton.Api.Chat.Message", b =>
                {
                    b.HasOne("Spilton.Api.Chat.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Spilton.Api.Documents.Document", b =>
                {
                    b.HasOne("Spilton.Api.Preparation.Space", "Space")
                        .WithMany()
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Spilton.Api.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Space");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Spilton.Api.Documents.DocumentChunk", b =>
                {
                    b.HasOne("Spilton.Api.Documents.Document", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Spilton.Api.Preparation.ExamStage", b =>
                {
                    b.HasOne("Spilton.Api.Preparation.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("Spilton.Api.Preparation.Goal", b =>
                {
                    b.HasOne("Spilton.Api.Preparation.Space", "Space")
                        .WithMany()
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Spilton.Api.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Space");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Spilton.Api.Preparation.Memory", b =>
                {
                    b.HasOne("Spilton.Api.Preparation.Space", "Space")
                        .WithMany()
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Spilton.Api.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Space");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Spilton.Api.Preparation.Space", b =>
                {
                    b.HasOne("Spilton.Api.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Spilton.Api.Preparation.StudyPlan", b =>
                {
                    b.HasOne("Spilton.Api.Preparation.Space", "Space")
                        .WithMany()
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Spilton.Api.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Space");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Spilton.Api.Preparation.StudyPlanItem", b =>
                {
                    b.HasOne("Spilton.Api.Preparation.StudyPlan", "StudyPlan")
                        .WithMany("Items")
                        .HasForeignKey("StudyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spilton.Api.Preparation.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StudyPlan");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Spilton.Api.Preparation.Subject", b =>
                {
                    b.HasOne("Spilton.Api.Preparation.ExamStage", "ExamStage")
                        .WithMany()
                        .HasForeignKey("ExamStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExamStage");
                });

            modelBuilder.Entity("Spilton.Api.Preparation.Topic", b =>
                {
                    b.HasOne("Spilton.Api.Preparation.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Spilton.Api.Preparation.UserExamProfile", b =>
                {
                    b.HasOne("Spilton.Api.Preparation.ExamStage", "ExamStage")
                        .WithMany()
                        .HasForeignKey("ExamStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Spilton.Api.Preparation.Space", "Space")
                        .WithMany()
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Spilton.Api.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExamStage");

                    b.Navigation("Space");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Spilton.Api.Preparation.UserTopicProgress", b =>
                {
                    b.HasOne("Spilton.Api.Preparation.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Spilton.Api.Preparation.UserExamProfile", "UserExamProfile")
                        .WithMany()
                        .HasForeignKey("UserExamProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");

                    b.Navigation("UserExamProfile");
                });

            modelBuilder.Entity("UserRoles", b =>
                {
                    b.HasOne("Spilton.Api.Data.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spilton.Api.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Spilton.Api.Chat.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Spilton.Api.Documents.Document", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("Spilton.Api.Preparation.StudyPlan", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
