"use client";
import { useEffect, useRef, useState } from 'react';
import { FileText, Upload, X, Trash2 } from 'lucide-react';
import { chatRequest, type Citation } from '@/lib/chat-client';
export type UploadedDocument = { id:string;name:string;contentType:string;size:number;category:string;status:string;error:string|null;pageCount:number|null;chunkCount:number;createdAt:string };
export function DocumentsPanel({open,onClose,documents,refresh,selected,onSelect,onUpload,busy,uploadError}:{open:boolean;onClose:()=>void;documents:UploadedDocument[];refresh:()=>Promise<void>;selected:string[];onSelect:(ids:string[])=>void;onUpload:(file:File)=>Promise<void>;busy:boolean;uploadError:string}) {
  const input=useRef<HTMLInputElement>(null);const [removing,setRemoving]=useState<UploadedDocument|null>(null);const [error,setError]=useState('');const [deleting,setDeleting]=useState(false);
  if(!open)return null;
  async function remove(){if(!removing)return;setDeleting(true);try{await chatRequest(`/documents/${removing.id}`,'DELETE');onSelect(selected.filter(id=>id!==removing.id));setRemoving(null);await refresh();}catch(e){setError((e as Error).message);}finally{setDeleting(false);}}
  return <div className="sp-modal-backdrop"><section className="sp-modal sp-documents" role="dialog" aria-modal="true" aria-labelledby="documents-title"><button className="sp-modal-close" aria-label="Close documents" onClick={onClose}><X size={20}/></button><h2 id="documents-title">Your documents</h2><p>Upload PDF, TXT or DOCX files up to 5 MB. Once processing finishes, select up to five files to ask questions about them. Relevant excerpts are shared with the AI provider.</p>
    <input ref={input} className="sr-only" type="file" aria-label="Upload document" accept=".pdf,.txt,.docx" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void onUpload(file);}}/>
    <button className="sp-document-upload" disabled={busy} onClick={()=>input.current?.click()}><Upload size={16}/>{busy?'Uploading…':'Upload document'}</button><button className="sp-document-refresh" onClick={()=>void refresh().catch(e=>setError((e as Error).message))}>Refresh documents</button>
    {(error||uploadError)&&<p role="alert" className="error-message">{error||uploadError}</p>}
    <div className="sp-document-list">{!documents.length&&!error&&!uploadError&&<p>No documents yet. Upload a file to begin.</p>}{documents.map(doc=><article key={doc.id} className="sp-document-card"><FileText size={22}/><div><strong>{doc.name}</strong><small>{doc.name.split('.').at(-1)?.toUpperCase()} · {(doc.size/1024).toFixed(1)} KB · {new Date(doc.createdAt).toLocaleDateString()}</small><span className={`sp-document-status status-${doc.status}`}>{doc.status==='UPLOADED'?'Uploaded — waiting':doc.status==='PROCESSING'?'Processing…':doc.status==='READY'?'Ready':doc.status==='FAILED'?'Failed':doc.status}</span>{doc.status==='READY'&&<small>{doc.pageCount ? `${doc.pageCount} pages · `:''}{doc.chunkCount} chunks · {doc.category}</small>}{doc.error&&<p>{doc.error}</p>}
    <label><input type="checkbox" aria-label={`Select ${doc.name}`} checked={selected.includes(doc.id)} disabled={doc.status!=='READY'||(!selected.includes(doc.id)&&selected.length>=5)} onChange={e=>onSelect(e.target.checked?[...selected,doc.id]:selected.filter(id=>id!==doc.id))}/> Use for chat</label></div><button aria-label={`Delete document ${doc.name}`} disabled={doc.status==='PROCESSING'} onClick={()=>setRemoving(doc)}><Trash2 size={16}/></button></article>)}</div>
    {removing&&<div className="sp-document-confirm"><p>Delete “{removing.name}”, its stored file, chunks and embeddings?</p><button disabled={deleting} onClick={()=>setRemoving(null)}>Cancel deletion</button><button disabled={deleting} onClick={()=>void remove()}>{deleting?'Deleting…':'Confirm delete document'}</button></div>}
    <button className="sp-settings-done" onClick={onClose}>Use selected documents ({selected.length})</button></section></div>;
}
export function Citations({items}:{items:Citation[]}) {
  const [selected,setSelected]=useState<Citation|null>(null);const [source,setSource]=useState('');const [error,setError]=useState('');
  useEffect(()=>{if(!selected||selected.url)return;let alive=true;chatRequest<{content:string}>(`/documents/${selected.documentId}/chunks/${selected.chunkId}`).then(data=>{if(alive)setSource(data.content);}).catch(()=>{if(alive)setError('This source is no longer available. It may have been deleted.');});return()=>{alive=false;};},[selected]);
  if(!items.length)return null;
  return <div className="sp-citations"><strong>Retrieved sources</strong>{items.map(c=>c.url?<a key={c.number} href={c.url} target="_blank" rel="noopener noreferrer">[{c.number}] {c.name} · {new URL(c.url).hostname}{c.sourceType?` · ${c.sourceType.replace('_',' ')}`:''}</a>:<button key={c.number} onClick={()=>{setSource('');setError('');setSelected(c);}}>[{c.number}] {c.name}{c.page?` — Page ${c.page}`:c.section?` — ${c.section}`:''}{c.sourceType?` · ${c.sourceType.replace('_',' ')}`:''}</button>)}{selected&&<div className="sp-modal-backdrop"><section role="dialog" aria-modal="true" aria-label="Source excerpt" className="sp-modal sp-source"><button className="sp-modal-close" aria-label="Close source" onClick={()=>setSelected(null)}><X size={18}/></button><h2>Source [{selected.number}]</h2><p>{selected.name}{selected.page?` — Page ${selected.page}`:selected.section?` — ${selected.section}`:''}</p>{error?<p role="alert">{error}</p>:<pre>{source||'Loading source…'}</pre>}</section></div>}</div>;
}
