"use client";
import {useEffect,useState,useSyncExternalStore,type FormEvent} from 'react';
import {chatRequest} from '@/lib/chat-client';
import {Citations,type UploadedDocument} from './documents-panel';
import {useRouter} from 'next/navigation';
import './preparation.css';import './documents.css';import './chat.css';
type Resource={id:string;kind:string;title:string;organization:string;sourceUrl:string|null;sourceType:string;verification:string;verifiedAt:string|null;status:string;documentId:string|null;publishedDate:string|null;year:number|null;stage:string;subject:string;category:string;summary:string;isSaved:boolean};
type Field={id:string;name:string;quote:string;page:number|null;chunkId:string;section:string|null};
type Detail={resource:Resource;fields:Field[];paperAnalysis:{detectedQuestionCount:number;extractionStatus:string;topics:{topic:string;count:number}[];questions:string[];methodology:string}|null;relevance:{score:number;signals:string[]}|null;notice:string};
type Eligibility={result:{overall:string;notice:string;results:{rule:string;state:string;reason:string;userDataUsed:string|number|null;source:{quote:string;chunkId:string;page:number|null;section:string|null}|null}[]};sourceType:string;verification:string;documentId:string|null};
const subscribe=()=>()=>{};
const categories=['Government Schemes','Economy','Appointments','Awards','Science and Technology','International','Sports','Environment','Defence','Important Reports','OTHER'];
type PrepCatalog={exams:{id:string;name:string}[];stages:{id:string;examId:string;name:string}[];subjects:{id:string;examStageId:string;name:string}[]};
const officialPortals:Record<string,{label:string;url:string}>={SSC:{label:'SSC official portal',url:'https://ssc.gov.in/'},UPSC:{label:'UPSC previous question papers',url:'https://upsc.gov.in/examinations/previous-question-papers'},APPSC:{label:'APPSC official syllabus and question papers',url:'https://portal-psc.ap.gov.in/HomePages/GroupsSyllabus'},RRB:{label:'Indian Railways official portal',url:'https://indianrailways.gov.in/'},Banking:{label:'IBPS official portal',url:'https://www.ibps.in/'}};
export function GovernmentPanel({space}:{space:string}){const router=useRouter();const hydrated=useSyncExternalStore(subscribe,()=>true,()=>false);
 const [items,setItems]=useState<Resource[]>([]),[documents,setDocuments]=useState<UploadedDocument[]>([]),[spaces,setSpaces]=useState<{id:string;name:string}[]>([]),[catalog,setCatalog]=useState<PrepCatalog>({exams:[],stages:[],subjects:[]}),[kind,setKind]=useState('NOTIFICATION'),[filters,setFilters]=useState(''),[detail,setDetail]=useState<Detail|null>(null),[eligibility,setEligibility]=useState<Eligibility|null>(null),[compare,setCompare]=useState<string[]>([]),[comparison,setComparison]=useState<{items:{resource:Resource;fields:Field[]}[]}|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[selectedDoc,setSelectedDoc]=useState(''),[filterExam,setFilterExam]=useState(''),[filterStage,setFilterStage]=useState(''),[filterSubject,setFilterSubject]=useState(''),[filterPeriod,setFilterPeriod]=useState('');
 const exams=Array.isArray(catalog?.exams)?catalog.exams:[];const stages=Array.isArray(catalog?.stages)?catalog.stages:[];const subjects=Array.isArray(catalog?.subjects)?catalog.subjects:[];const selectedExam=exams.find(e=>e.id===filterExam);const selectedFamily=selectedExam?.name.match(/SSC|UPSC|APPSC|RRB|Banking/i)?.[0];const official=selectedFamily?officialPortals[Object.keys(officialPortals).find(k=>k.toLowerCase()===selectedFamily.toLowerCase())||'']:undefined;const filteredStages=stages.filter(s=>s.examId===filterExam);const filteredSubjects=subjects.filter(s=>s.examStageId===filterStage);
 const scope=space?'spaceId='+space+'&':'';
 useEffect(()=>{let alive=true;Promise.all([chatRequest<{items:Resource[]}>(`/government/resources?${scope}kind=${kind}${filters}`),chatRequest<{items:UploadedDocument[]}>('/documents?'+scope),chatRequest<{items:{id:string;name:string}[]}>('/spaces'),chatRequest<PrepCatalog>('/preparation/catalog')]).then(([r,d,s,c])=>{if(alive){setItems(r.items);setDocuments(d.items);setSpaces(s.items);setCatalog(c);}}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[scope,kind,filters]);
 async function refresh(){setItems((await chatRequest<{items:Resource[]}>(`/government/resources?${scope}kind=${kind}${filters}`)).items);setDocuments((await chatRequest<{items:UploadedDocument[]}>('/documents?'+scope)).items);}
 async function run(job:()=>Promise<void>){setBusy(true);setError('');try{await job();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function values(e:FormEvent<HTMLFormElement>){e.preventDefault();return Object.fromEntries(new FormData(e.currentTarget));}
 async function open(id:string){await run(async()=>{setDetail(await chatRequest<Detail>('/government/resources/'+id));setEligibility(null);});}
 function ask(r:Resource,prompt:string){const p=new URLSearchParams({docs:r.documentId||'',mode:'research',prompt});if(space)p.set('space',space);return '/chat?'+p.toString();}
 async function upload(file:File){await run(async()=>{if(file.size>5*1024*1024)throw new Error('Upload at most 5 MB.');const form=new FormData();form.append('file',file);form.append('category',kind==='NOTIFICATION'?'NOTIFICATION':kind==='PYQ'?'PREVIOUS_YEAR_PAPER':'OTHER');if(space)form.append('spaceId',space);const r=await fetch('/api/chat/documents',{method:'POST',body:form});const d=await r.json();if(!r.ok)throw new Error(d.title||'Upload failed');setNotice('Uploaded. Processing document and real embeddings…');for(let i=0;i<90;i++){await new Promise(resolve=>setTimeout(resolve,2000));const status=await chatRequest<UploadedDocument>('/documents/'+d.id);if(status.status==='FAILED')throw new Error(status.error||'Processing failed.');if(status.status==='READY'){await refresh();setSelectedDoc(d.id);setNotice('Document Ready. Complete the source registration below.');return;}}throw new Error('Processing is still pending. Refresh the document list later.');});}
 return <main className="prep"><header><a href={'/prepare'+(space?'?space='+space:'')}>✦ Spilton AI · Dashboard</a><h1>Government exam resources</h1><p>Official evidence first. A private library of notifications, permitted papers and concise current-affairs notes.</p><label>Resource Space<select value={space} onChange={e=>{router.push('/government'+(e.target.value?'?space='+e.target.value:''));}}><option value="">General</option>{spaces.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><p><b>Live search is not connected.</b> Research reads your selected documents. Freshness, later updates and corrigenda need checking against the official portal.</p></header>
 {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <nav>{[['NOTIFICATION','Notifications & Eligibility'],['PYQ','Previous Year Papers'],['CURRENT_AFFAIRS','Current Affairs']].map(([value,label])=><button key={value} disabled={busy||!hydrated} onClick={()=>{setKind(value);setDetail(null);setComparison(null);setCompare([]);setFilters('');setFilterExam('');setFilterStage('');setFilterSubject('');setFilterPeriod('');}}>{label}</button>)}</nav>
 <section><h2>{kind==='CURRENT_AFFAIRS'?"Today’s Current Affairs · manual sources":kind==='PYQ'?'Previous Year Papers library':'Notification library'}</h2>{kind==='CURRENT_AFFAIRS'&&<p>No automatic news feed. Dates, summaries and relevance are manually supplied or rules-based; open original sources to verify.</p>}{kind==='PYQ'&&<p>Select exam, stage, subject and period. Spilton shows only papers in your verified library; when none exist, use the official portal or upload a legally available copy.</p>}<form onSubmit={e=>{const v=values(e);const p=new URLSearchParams();for(const [k,value] of Object.entries(v))if(value)p.set(k,String(value));if(filterStage)p.set('stage',catalog.stages.find(s=>s.id===filterStage)?.name||'');if(filterPeriod)p.set('yearFrom',String(new Date().getFullYear()-Number(filterPeriod)+1));setFilters('&'+p.toString());}}><label>Search<input name="search" maxLength={200} placeholder="Paper or notification title"/></label><label>Exam / department<select name="examId" value={filterExam} onChange={e=>{setFilterExam(e.target.value);setFilterStage('');setFilterSubject('');}}><option value="">All exams</option>{exams.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label>Stage<select value={filterStage} disabled={!filterExam} onChange={e=>{setFilterStage(e.target.value);setFilterSubject('');}}><option value="">All stages</option>{filteredStages.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Subject<select name="subject" value={filterSubject} disabled={!filterStage} onChange={e=>setFilterSubject(e.target.value)}><option value="">All subjects</option>{filteredSubjects.map(s=><option key={s.id} value={s.name}>{s.name}</option>)}</select></label>{kind==='PYQ'?<label>Paper period<select value={filterPeriod} onChange={e=>setFilterPeriod(e.target.value)}><option value="">All available years</option><option value="2">Past 2 years</option><option value="5">Past 5 years</option><option value="10">Past 10 years</option></select></label>:<label>Organization<input name="organization"/></label>}<label>Exact year<input name="year" type="number" min={1950} max={2100}/></label><label>Status<select name="status"><option value="">All available</option><option>REGISTERED</option><option>ANALYZED</option><option>ARCHIVED</option></select></label>{kind==='CURRENT_AFFAIRS'&&<label>Publication date<input type="date" name="date"/></label>}<button>Show available resources</button><button type="button" onClick={()=>{setFilters('');setFilterExam('');setFilterStage('');setFilterSubject('');setFilterPeriod('');}}>Clear filters</button></form>{kind==='PYQ'&&official&&<p><b>No paper in Spilton?</b> <a href={official.url} target="_blank" rel="noopener noreferrer">Open {official.label}</a>. Verify the exam, year and notice before downloading.</p>}
 {!items.length&&<p>No matching resources. Upload or register your first source below.</p>}{items.map(r=><article key={r.id}><h3><b>{r.title}</b></h3><p>{r.organization||'Organization not supplied'} · {r.sourceType} · {r.verification} · {r.publishedDate||'Publication date unknown'}</p>{r.summary&&<p>Manual summary · not independently verified: {r.summary}</p>}<button disabled={busy||!hydrated} onClick={()=>void open(r.id)}>View details</button>{r.documentId&&<a href={ask(r,kind==='PYQ'?'Analyse the questions and recurring concepts in this paper. Distinguish observations from uncertain extraction.':'What does this document say? Cite the actual pages.')}> Analyse with AI / RAG </a>}{r.sourceUrl&&<a href={r.sourceUrl} target="_blank" rel="noopener noreferrer"> Source link ({r.sourceType}) </a>}{kind==='PYQ'&&<>{r.documentId&&<a href={'/api/chat/government/resources/'+r.id+'/download'}> Download your uploaded copy </a>}<a href={"/mocks?"+new URLSearchParams({...(space?{space}:{}),paper:r.id})}> Review readiness / Take as Mock </a>{r.documentId&&<a href={ask(r,'Help me practice a question from this paper, quoting its source. Do not invent questions as original PYQs.')}> Use for practice </a>}</>}{kind==='NOTIFICATION'&&<label><input type="checkbox" checked={compare.includes(r.id)} disabled={!compare.includes(r.id)&&compare.length>=2} onChange={e=>setCompare(e.target.checked?[...compare,r.id]:compare.filter(id=>id!==r.id))}/> Compare notification</label>}<button disabled={busy||!hydrated} onClick={()=>void run(async()=>{await chatRequest('/government/resources/'+r.id,'PATCH',{title:r.title,status:r.status,isSaved:!r.isSaved});await refresh();})}>{r.isSaved?'Unsave':'Save item'}</button><button disabled={busy||!hydrated} onClick={()=>{if(confirm('Remove this library entry? Its uploaded document remains in Files.'))void run(async()=>{await chatRequest('/government/resources/'+r.id,'DELETE');if(detail?.resource.id===r.id)setDetail(null);await refresh();});}}>Remove entry</button><hr/></article>)}{compare.length===2&&<button onClick={()=>void run(async()=>setComparison(await chatRequest('/government/compare','POST',{ids:compare})))}>Compare selected notifications</button>}</section>
 <section><h2>Upload / register source</h2><p>Source categories cannot be self-promoted to Official. Server-reviewed URL and file-hash matches receive verified labels. A link alone is metadata, not fetched evidence.</p><label>Upload source document<input aria-label="Upload government document" type="file" accept=".pdf,.txt,.docx" disabled={busy||!hydrated} onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)void upload(f);}}/></label><button disabled={busy||!hydrated} onClick={()=>void run(refresh)}>Refresh Ready documents</button><form onSubmit={e=>{const v=values(e);void run(async()=>{await chatRequest('/government/resources','POST',{spaceId:space||null,kind,title:v.title,organization:v.organization,sourceUrl:v.url||null,documentId:selectedDoc||null,examId:v.exam||null,notificationNumber:v.number,publishedDate:v.date||null,year:v.year?Number(v.year):null,stage:v.stage,subject:v.subject,language:v.language,shift:v.shift,category:v.category||'OTHER',summary:v.summary||'',rightsConfirmed:v.rights==='on'});await refresh();setNotice('Source registered. Review detected excerpts and verification labels.');});}}>
 <label>Title / headline<input name="title" required maxLength={200}/></label><label>Organization<input name="organization" maxLength={120}/></label><label>Source URL<input name="url" type="url" placeholder="https://official-portal/..." maxLength={2000}/></label><label>Ready document<select value={selectedDoc} onChange={e=>setSelectedDoc(e.target.value)}><option value="">URL metadata only</option>{documents.filter(d=>d.status==='READY').map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Target exam<select name="exam"><option value="">Not specified</option>{exams.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label>Notification number<input name="number" maxLength={100}/></label><label>Publication date<input type="date" name="date"/></label><label>Paper year<input type="number" name="year" min={1950} max={2100}/></label><label>Stage<input name="stage" maxLength={80}/></label><label>Subject<input name="subject" maxLength={80}/></label><label>Language<input name="language" maxLength={50}/></label><label>Shift / date label<input name="shift" maxLength={100}/></label>{kind==='CURRENT_AFFAIRS'&&<><label>Category<select name="category">{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Concise derived summary (do not copy articles)<input name="summary" maxLength={700}/></label></>}{kind==='PYQ'&&<label><input type="checkbox" name="rights" required/> This is official/publicly permitted or my own permitted material, not paid coaching content</label>}<button disabled={busy||!hydrated}>{busy?'Working…':'Register source'}</button></form></section>
 {detail&&<section><h2>{detail.resource.title}</h2><p>{detail.resource.sourceType} · {detail.resource.verification}</p><p>{detail.notice}</p>{detail.fields.map(f=><div key={f.id}><h3><b>{f.name}</b></h3><blockquote>{f.quote}</blockquote>{detail.resource.documentId&&<Citations items={[{number:1,documentId:detail.resource.documentId,chunkId:f.chunkId,name:detail.resource.title,page:f.page,section:f.section,excerpt:''}]}/>}</div>)}{detail.paperAnalysis&&<><h3>Paper analytics · extraction review required</h3><p>{detail.paperAnalysis.extractionStatus} · {detail.paperAnalysis.detectedQuestionCount} detected numbered question lines</p><p>{detail.paperAnalysis.methodology}</p>{detail.paperAnalysis.topics.map(t=><p key={t.topic}>{t.topic}: {t.count}</p>)}<details><summary>Detected question excerpts</summary>{detail.paperAnalysis.questions.map((q,i)=><p key={i}>{q}</p>)}</details></>}{detail.relevance&&<><h3>Rules-based exam relevance: {detail.relevance.score}/100</h3><ul>{detail.relevance.signals.map(s=><li key={s}>{s}</li>)}</ul></>}
 {detail.resource.kind==='NOTIFICATION'&&<><h3>Eligibility screening</h3><p>Use your age at the notification cutoff. No Aadhaar, PAN, date of birth, registration ID or credentials are needed. Inputs are not stored. Complex rules need manual review.</p><form onSubmit={e=>{const v=values(e);void run(async()=>setEligibility(await chatRequest('/government/resources/'+detail.resource.id+'/eligibility','POST',{age:v.age?Number(v.age):null,education:v.education||null,reviewedAllRules:v.review==='on',needsRelaxation:v.relax==='on'})));}}><label>Age at stated cutoff (optional)<input name="age" type="number" min={14} max={100}/></label><label>Education level<select name="education"><option value="">Not supplied</option><option value="BELOW_BACHELOR">Below bachelor degree</option><option value="BACHELOR_OR_HIGHER">Bachelor degree or higher</option></select></label><label><input type="checkbox" name="relax"/> I need an age relaxation or exception assessed</label><label><input type="checkbox" name="review"/> I reviewed the complete source for other conditions, post and cutoff dates</label><button disabled={busy||!hydrated}>Check eligibility</button></form>{eligibility&&<div><h3>{eligibility.result.overall.replaceAll('_',' ')}</h3><p>{eligibility.result.notice}</p>{eligibility.result.results.map((r,i)=><article key={i}><b>{r.rule}: {r.state}</b><p>Input: {r.userDataUsed??'Not supplied / not needed'} · {r.reason}</p>{r.source&&eligibility.documentId&&<Citations items={[{number:i+1,documentId:eligibility.documentId,chunkId:r.source.chunkId,name:detail.resource.title,page:r.source.page,section:r.source.section,excerpt:''}]}/>}</article>)}</div>}</>}
 </section>}{comparison&&<section><h2>Compare notification evidence</h2><p>Unknown or omitted fields are not proof that a condition changed. Review complete sources and later corrigenda.</p><div className="prep-grid">{comparison.items.map(r=><div key={r.resource.id}><h3>{r.resource.title} · {r.resource.sourceType}</h3>{r.fields.map((f,i)=><p key={i}><b>{f.name}</b>: {f.quote} {f.page?'— Page '+f.page:''}</p>)}</div>)}</div></section>}
 </main>;
}
