"use client";
import {useEffect,useState,type FormEvent} from 'react';
import {chatRequest} from '@/lib/chat-client';
import {useRouter} from 'next/navigation';
import {apiRequest} from '@/lib/api-client';
import {MockAttemptView} from './mock-attempt';
import './preparation.css';import './mocks.css';
type Topic={id:string;name:string;subject:string;subjectId:string;examStageId:string};
type Catalog={bank:{topicId:string;name:string;subject:string;subjectId:string;examStageId:string;difficulty:string;count:number}[];topics:Topic[];tests:{id:string;title:string;description:string;examStageId:string;durationSeconds:number;count:number;sections:{name:string;marksCorrect:number;negativeMarks:number}[]}[]};
type History={id:string;title:string;status:string;startedAt:string;score:number|null;accuracyPercent:number|null;timeTakenSeconds:number};
type Paper={id:string;title:string;spaceId:string|null;reviewedCount:number;canConvert:boolean;reason:string;chunks:{id:string;content:string;pageNumber:number|null}[]};
export function MockWorkspace({space,attemptId,paperId}:{space:string;attemptId?:string;paperId?:string}){
 const suffix=space?'?space='+space:'';
 return <main className="prep mocks"><header className="mock-brand"><a href={'/prepare'+suffix}>✦ Spilton AI</a><nav><a href={'/mocks'+suffix}>Mock Tests & Practice</a><a href={'/government'+suffix}>Paper library</a><a href={'/chat'+suffix}>Chat</a><button onClick={async()=>{await apiRequest('/auth/logout',{});location.replace('/login?returnTo='+encodeURIComponent(location.pathname+location.search));}}>Log out</button></nav></header>{attemptId?<MockAttemptView id={attemptId} space={space}/>:<MockCatalog space={space} paperId={paperId}/>}</main>;
}
function MockCatalog({space,paperId}:{space:string;paperId?:string}){const router=useRouter();
 const [catalog,setCatalog]=useState<Catalog|null>(null),[history,setHistory]=useState<History[]>([]),[stages,setStages]=useState<{id:string;name:string;examId:string}[]>([]),[exams,setExams]=useState<{id:string;name:string}[]>([]),[stage,setStage]=useState(''),[topic,setTopic]=useState(''),[subject,setSubject]=useState(''),[difficulty,setDifficulty]=useState(''),[count,setCount]=useState(5),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[paper,setPaper]=useState<Paper|null>(null);
 const query=space?'?spaceId='+space:'';
 useEffect(()=>{let alive=true;Promise.all([chatRequest<Catalog>('/mocks/catalog'+query),chatRequest<{items:History[]}>('/mocks/attempts'+query),chatRequest<{stages:{id:string;name:string;examId:string}[];exams:{id:string;name:string}[]}>('/preparation/catalog'),paperId?chatRequest<Paper>('/mocks/papers/'+paperId+'/status'):Promise.resolve(null)]).then(([c,h,e,p])=>{if(alive){setCatalog(c);setHistory(h.items);setStages(e.stages);setExams(e.exams);setPaper(p);}}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[query,paperId]);
 async function reload(){setCatalog(await chatRequest<Catalog>('/mocks/catalog'+query));setHistory((await chatRequest<{items:History[]}>('/mocks/attempts'+query)).items);if(paperId)setPaper(await chatRequest<Paper>('/mocks/papers/'+paperId+'/status'));}
 async function run(job:()=>Promise<void>){setBusy(true);setError('');try{await job();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function view(id:string){router.push('/mocks?'+new URLSearchParams({...space?{space}:{},attempt:id}));}
 async function start(id:string){const a=await chatRequest<{id:string}>('/mocks/tests/'+id+'/attempts','POST',{spaceId:space||null,startKey:crypto.randomUUID()});view(a.id);}
 const availableStageIds=new Set(catalog?.bank.filter(b=>b.count>0).map(b=>b.examStageId)||[]);const pool=catalog?.bank.filter(b=>b.examStageId===stage&&(!subject||b.subjectId===subject)&&(!topic||b.topicId===topic)&&(!difficulty||b.difficulty===difficulty))||[];const available=pool.reduce((n,b)=>n+b.count,0);const topics=catalog?.topics.filter(t=>t.examStageId===stage)||[];
 function practice(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const intent=((e.nativeEvent as SubmitEvent).submitter as HTMLButtonElement)?.value;void run(async()=>{const request={spaceId:space||null,examStageId:stage,count:intent==='paper'?Math.min(Number(f.get('count')),paper?.reviewedCount||0):Number(f.get('count')),subjectId:subject||null,topicId:topic||null,difficulty:difficulty||null,weakAreas:intent==='weak',durationSeconds:Number(f.get('minutes'))*60,marksCorrect:Number(f.get('marks')),negativeMarks:Number(f.get('negative')),floorAtZero:f.get('floor')==='on'};const c=await chatRequest<{id:string}>(intent==='paper'?'/mocks/papers/'+paperId+'/convert':'/mocks/practice','POST',request);await start(c.id);});}
 return <><h1>Mock Tests & Practice</h1><p>Choose your exam first, then a test or subject to practise.</p>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{!catalog?<p role="status">Loading your practice workspace…</p>:<>
 <section><h2>Choose your exam</h2><label>Exam and stage<select aria-label="Choose target exam" value={stage} onChange={e=>{setStage(e.target.value);setTopic('');setSubject('');}}><option value="">Select your target exam</option>{stages.map(s=><option key={s.id} value={s.id}>{exams.find(e=>e.id===s.examId)?.name} · {s.name}</option>)}</select></label>{stage&&!availableStageIds.has(stage)&&<p>Practice questions for this exam are not available yet.</p>}<a href={'/prepare'+(space?'?space='+space:'')}>Manage my preparation target</a></section>
 <section><h2>Available tests</h2>{!stage&&<p>Select an exam above to see its tests.</p>}{stage&&!catalog.tests.some(t=>t.examStageId===stage)&&<p>No ready-made tests for this exam yet.</p>}{catalog.tests.filter(t=>t.examStageId===stage).map(t=><article className="mock-test-card" key={t.id}><h3>{t.title}</h3><p>{t.description}</p><p>{t.count} questions · {Math.ceil(t.durationSeconds/60)} minutes</p><p>{t.sections.map(s=>`${s.name}: +${s.marksCorrect} / −${s.negativeMarks}`).join(' · ')}</p><button disabled={busy} onClick={()=>void run(()=>start(t.id))}>Start / resume {t.title}</button></article>)}</section>
 {paper&&<section><h2>PYQ → Mock: {paper.title}</h2><p>{paper.reason}</p><p>{paper.reviewedCount} reviewed questions. The answer key is manually checked, not automatically verified.</p>{!paper.canConvert&&<button disabled>Take as Mock · review required</button>}<details><summary>Actual extracted source (first 50 chunks)</summary>{paper.chunks.map(c=><div key={c.id}><strong>{c.pageNumber?'Page '+c.pageNumber:'Source excerpt'} · {c.id}</strong><pre>{c.content}</pre></div>)}</details></section>}
 {stage&&<section><h2>Practise by subject</h2><p>Choose a subject and topic. Practice requires enough available questions.</p><form onSubmit={practice}><label>Subject<select value={subject} onChange={e=>{setSubject(e.target.value);setTopic('');}}><option value="">All available subjects</option>{Array.from(new Map(topics.map(t=>[t.subjectId,t.subject]))).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>Topic<select value={topic} onChange={e=>setTopic(e.target.value)}><option value="">All available topics</option>{topics.filter(t=>!subject||t.subjectId===subject).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Difficulty<select value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option value="">All</option><option>EASY</option><option>MEDIUM</option><option>HARD</option></select></label><label>Question count ({available} available)<select name="count" aria-label="Practice question count" value={Math.min(count,available)||1} onChange={e=>setCount(Number(e.target.value))} disabled={!available}>{Array.from({length:Math.min(50,available)},(_,i)=><option key={i+1}>{i+1}</option>)}</select></label><label>Duration (minutes)<input name="minutes" type="number" min={1} max={120} defaultValue={10} required/></label><details><summary>Scoring options</summary><label>Marks per correct answer<input name="marks" type="number" min={.01} max={20} step={.01} defaultValue={2} required/></label><label>Negative marks per wrong answer<input name="negative" type="number" min={0} max={20} step={.01} defaultValue={.5} required/></label><label><input type="checkbox" name="floor"/> Floor total score at zero</label></details><button disabled={busy||!available} value="custom">Start custom practice</button><button disabled={busy||!available} value="weak">Practice Weak Areas</button>{paper?.canConvert&&<button disabled={busy} value="paper">Take reviewed paper as Mock</button>}</form><p>Weak-area practice helps you revisit recent mistakes.</p></section>}
 <section><h2>Attempt History</h2>{!history.length?<p>No attempts yet.</p>:history.map(a=><article className="mock-test-card" key={a.id}><b>{a.title}</b><p>{new Date(a.startedAt).toLocaleString()} · {a.status} · Score {a.score??'Pending'} · Accuracy {a.accuracyPercent===null?'—':a.accuracyPercent+'%'} · {a.timeTakenSeconds}s</p><button onClick={()=>view(a.id)}>{a.status==='ACTIVE'?'Resume attempt':'View result'}</button></article>)}</section>
 <section><details><summary>{paper?'Review paper questions':'Add your own practice questions (optional)'}</summary><p>{paper?'The question and all four labelled options must match the source chunks. Review the answer key yourself. Missing or malformed extraction is rejected.':'These private questions are labelled USER_AUTHORED, never official PYQ or AI-generated.'}</p><form key={stage+(paper?.id||'')} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(async()=>{await chatRequest(paper?'/mocks/papers/'+paper.id+'/questions':'/mocks/questions','POST',{spaceId:space||null,topicId:f.get('topic'),text:f.get('question'),options:[0,1,2,3].map(i=>String(f.get('option'+i))),correctOptionIndex:Number(f.get('correct')),explanation:f.get('explanation'),difficulty:f.get('difficulty'),sourceChunkIds:f.getAll('chunks'),reviewed:f.get('reviewed')==='on'});await reload();setNotice('Reviewed question saved with its provenance.');});}}><label>Question topic<select name="topic" required>{topics.map(t=><option key={t.id} value={t.id}>{t.subject} · {t.name}</option>)}</select></label><label>Question text<textarea name="question" required maxLength={3000}/></label>{[0,1,2,3].map(i=><label key={i}>Option {String.fromCharCode(65+i)}<input name={'option'+i} required maxLength={1000}/></label>)}<label>Correct option<select name="correct">{[0,1,2,3].map(i=><option key={i} value={i}>{String.fromCharCode(65+i)}</option>)}</select></label><label>Explanation<textarea name="explanation" required maxLength={3000}/></label><label>Question difficulty<select name="difficulty"><option>EASY</option><option>MEDIUM</option><option>HARD</option></select></label>{paper&&<label>Source chunks (select up to five)<select name="chunks" multiple required size={5}>{paper.chunks.map(c=><option key={c.id} value={c.id}>{c.pageNumber?'Page '+c.pageNumber:'Excerpt'} · {c.content.slice(0,80)}</option>)}</select></label>}<label><input name="reviewed" type="checkbox" required/> I reviewed the question, options, answer and explanation</label><button disabled={busy||!topics.length}>Save reviewed question</button></form></details></section>
 </>}</>;
}
