"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import {chatRequest,streamChat,type Conversation} from '@/lib/chat-client';
import type {Attempt,AnalysisGroup,MockQuestion} from '@/lib/mock-types';
import {MarkdownMessage} from './markdown-message';
function state(q:MockQuestion){return q.answer.markedForReview?(q.answer.optionId?'answered-review':'review'):q.answer.optionId?'answered':q.answer.visited?'unanswered':'not-visited';}
function clockText(seconds:number){return `${Math.floor(seconds/60).toString().padStart(2,'0')}:${(seconds%60).toString().padStart(2,'0')}`;}
export function MockAttemptView({id,space}:{id:string;space:string}){
 const [attempt,setAttempt]=useState<Attempt|null>(null),[index,setIndex]=useState(0),[remaining,setRemaining]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[confirmSubmit,setConfirmSubmit]=useState(false),[tutor,setTutor]=useState(''),[tutorBusy,setTutorBusy]=useState(false),[tutorLabel,setTutorLabel]=useState('');
 const revision=useRef(0);const saved=useRef<Attempt|null>(null),pending=useRef(false),anchor=useRef({server:0,local:0}),lastAuto=useRef(0),tutorController=useRef<AbortController|null>(null),tutorConversation=useRef<string|null>(null);
 const apply=useCallback((a:Attempt)=>{saved.current=a;anchor.current={server:Date.parse(a.serverNow),local:performance.now()};setAttempt(a);setRemaining(Math.max(0,Math.ceil((Date.parse(a.expiresAt)-Date.parse(a.serverNow))/1000)));},[]);
 const reload=useCallback(async()=>{const a=await chatRequest<Attempt>('/mocks/attempts/'+id);apply(a);return a;},[id,apply]);
 useEffect(()=>{let alive=true;async function boot(){try{let a=await chatRequest<Attempt>('/mocks/attempts/'+id);if(!alive)return;const position=Math.max(0,Math.min(a.questions.length-1,Number(new URLSearchParams(location.search).get('q'))||0));const q=a.questions[position];if(a.status==='ACTIVE'&&!q.answer.visited)a=await chatRequest<Attempt>(`/mocks/attempts/${id}/answers/${q.id}`,'PATCH',{optionId:q.answer.optionId,markedForReview:q.answer.markedForReview,version:q.answer.version});if(alive){apply(a);setIndex(position);}}catch(e){if(alive)setError((e as Error).message);}}void boot();return()=>{alive=false;tutorController.current?.abort();};},[id,apply]);
 const submit=useCallback(async()=>{if(pending.current)return;revision.current++;pending.current=true;setBusy(true);setError('');try{apply(await chatRequest<Attempt>('/mocks/attempts/'+id+'/submit','POST',{}));setConfirmSubmit(false);}catch(e){setError((e as Error).message);}finally{pending.current=false;setBusy(false);}},[id,apply]);
 useEffect(()=>{const timer=setInterval(()=>{const a=saved.current;if(!a||a.status!=='ACTIVE')return;const server=anchor.current.server+performance.now()-anchor.current.local;const left=Math.max(0,Math.ceil((Date.parse(a.expiresAt)-server)/1000));setRemaining(left);if(left===0&&!pending.current&&performance.now()-lastAuto.current>5000){lastAuto.current=performance.now();void submit();}},500);const poll=setInterval(()=>{if(!pending.current&&saved.current?.status==='ACTIVE'){const version=revision.current;void chatRequest<Attempt>('/mocks/attempts/'+id).then(a=>{if(!pending.current&&version===revision.current)apply(a);}).catch(e=>setError(e.message));}},15000);return()=>{clearInterval(timer);clearInterval(poll);};},[reload,submit,id,apply]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(pending.current){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[]);
 async function navigate(next:number){if(pending.current||!saved.current)return;const current=saved.current;if(next<0||next>=current.questions.length)return;revision.current++;pending.current=true;setBusy(true);setError('');try{const q=current.questions[next];if(!q.answer.visited)apply(await chatRequest<Attempt>(`/mocks/attempts/${id}/answers/${q.id}`,'PATCH',{optionId:q.answer.optionId,markedForReview:q.answer.markedForReview,version:q.answer.version}));setIndex(next);const params=new URLSearchParams(location.search);params.set('q',String(next));window.history.replaceState(null,'','/mocks?'+params);}catch(e){setError((e as Error).message);await reload().catch(()=>{});}finally{pending.current=false;setBusy(false);}}
 async function answer(optionId:string|null,marked:boolean,next?:number){let savedSuccessfully=false;if(pending.current||!saved.current)return;const q=saved.current.questions[index];revision.current++;pending.current=true;setBusy(true);setError('');try{apply(await chatRequest<Attempt>(`/mocks/attempts/${id}/answers/${q.id}`,'PATCH',{optionId,markedForReview:marked,version:q.answer.version}));savedSuccessfully=true;}catch(e){setError((e as Error).message);await reload().catch(()=>{});}finally{pending.current=false;setBusy(false);}if(savedSuccessfully&&next!==undefined&&saved.current?.status==='ACTIVE')await navigate(next);}
 async function explain(q:MockQuestion,style:string){if(tutorBusy)return;setTutorBusy(true);setTutor('');setError('');const controller=new AbortController();tutorController.current=controller;try{const data=await chatRequest<{spaceId:string|null;prompt:string}>(`/mocks/attempts/${id}/tutor`,'POST',{questionId:q.id,style});const c=await chatRequest<Conversation>('/conversations','POST',{spaceId:data.spaceId});tutorConversation.current=c.id;await streamChat('/conversations/'+c.id+'/messages',{content:data.prompt,mode:'quick',model:'auto'},controller.signal,(type,data)=>{if(type==='start'){const message=data.message as {modelProvider:string};setTutorLabel(message.modelProvider==='Development'?'Development demo · not real AI':'Spilton tutor · '+message.modelProvider);}if(type==='delta')setTutor(t=>t+String(data.text));if(type==='done')setTutor((data.message as {content:string}).content);if(type==='error')setError(String(data.message));});}catch(e){if((e as Error).name!=='AbortError')setError((e as Error).message);}finally{setTutorBusy(false);tutorController.current=null;}}
 async function stopTutor(){if(tutorConversation.current)await chatRequest('/conversations/'+tutorConversation.current+'/stop','POST',{}).catch(()=>tutorController.current?.abort());}
 if(!attempt)return <section><h1>Opening saved attempt…</h1>{error&&<p role="alert">{error}</p>}<button onClick={()=>void reload().catch(e=>setError(e.message))}>Retry attempt</button></section>;
 const q=attempt.questions[index];const done=attempt.status==='SUBMITTED';const result=attempt.result;
 return <><header className="mock-exam-header"><div><h1>{attempt.title}</h1><p>{attempt.exam} · {attempt.stage} · {done?'Submitted':'Answers save automatically'}</p></div>{!done&&<><div className={remaining<60?'mock-timer urgent':'mock-timer'} role="timer" aria-label="Time remaining">{clockText(remaining)}</div><button disabled={busy} onClick={()=>setConfirmSubmit(true)}>Submit test</button></>}</header>{error&&<p role="alert">{error} <button onClick={()=>void reload().catch(e=>setError(e.message))}>Reload saved attempt</button></p>}
 {done&&result?<>
 <section aria-label="Test result"><h2>Your result</h2><div className="mock-stats"><div><b>{result.finalScore}</b><span>Final score</span></div><div><b>{result.accuracyPercent===null?'—':result.accuracyPercent+'%'}</b><span>Accuracy</span></div><div><b>{result.correct}</b><span>Correct</span></div><div><b>{result.incorrect}</b><span>Incorrect</span></div><div><b>{result.unattempted}</b><span>Unattempted</span></div><div><b>{clockText(result.timeTakenSeconds)}</b><span>Time taken</span></div></div><p>Raw score {result.rawScore} − negative marks {result.negativeMarks}{attempt.floorAtZero?' · total floored at zero':''}. {attempt.completionReason==='EXPIRED'?'Automatically submitted at the stored expiry time.':'Submitted by you.'}</p><p>{result.progressNotice}</p><a href={'/mocks'+(space?'?space='+space:'')}>Practice Weak Areas / attempt history</a></section>
 <section><h2>Subject analysis</h2><Analysis rows={result.subjects}/><h2>Topic analysis</h2><Analysis rows={result.topics}/></section>
 <section><h2>Question review</h2>{attempt.questions.map((question,i)=><article className="mock-review" key={question.id}><h3>{i+1}. {question.text}</h3><p>{question.subject} · {question.topic} · {question.sourceType}</p><p>Your answer: {question.options.find(o=>o.id===question.answer.optionId)?.text||'Unanswered'}</p><p><b>Correct answer: {question.options.find(o=>o.id===question.review?.correctOptionId)?.text}</b> · Score {question.review?.score}</p><p>{question.review?.explanation}</p><details><summary>Question provenance</summary><pre>{JSON.stringify(question.review?.source,null,2)}</pre></details><button disabled={tutorBusy} onClick={()=>void explain(question,'preferred')}>Explain with Spilton</button><button disabled={tutorBusy} onClick={()=>void explain(question,'simple')}>Simpler explanation</button><button disabled={tutorBusy} onClick={()=>void explain(question,'telugu')}>Telugu explanation</button><button disabled={tutorBusy} onClick={()=>void explain(question,'similar')}>Similar original practice</button></article>)}</section>
 {(tutor||tutorBusy)&&<section aria-label="Spilton tutor"><h2>{tutorLabel||'Spilton tutor'}</h2><MarkdownMessage content={tutor}/>{tutorBusy&&<><p role="status">Preparing a student-facing explanation…</p><button onClick={()=>void stopTutor()}>Stop explanation</button></>}<p>The tutor chat is saved in this Space’s chat history. Generated practice is original practice, not PYQ.</p></section>}
 </>:<div className="mock-exam-layout"><section className="mock-question"><nav className="mock-section-nav" aria-label="Test sections">{attempt.sections.map(s=><button key={s.id} disabled={busy} className={q.sectionId===s.id?'selected':''} onClick={()=>void navigate(attempt.questions.findIndex(q=>q.sectionId===s.id))}>{s.name}</button>)}</nav><p>Question {index+1} of {attempt.questions.length} · {q.subject} · {q.difficulty}</p><h2>{q.text}</h2><p className="mock-provenance">{q.sourceType} · {q.topic}</p><fieldset disabled={busy||remaining===0} aria-label="Answer options">{q.options.map((o,i)=><label className={`mock-option ${q.answer.optionId===o.id?'chosen':''}`} key={o.id}><input type="radio" name="answer" checked={q.answer.optionId===o.id} onChange={()=>void answer(o.id,q.answer.markedForReview)}/><b>{String.fromCharCode(65+i)}.</b> {o.text}</label>)}</fieldset><p role="status">{busy?'Saving…':'All displayed answers saved'}{q.answer.markedForReview?' · Marked for review':''}</p><div className="mock-controls"><button disabled={busy} onClick={()=>void answer(null,q.answer.markedForReview)}>Clear response</button><button disabled={busy||index===0} onClick={()=>void navigate(index-1)}>Previous</button><button disabled={busy||index===attempt.questions.length-1} onClick={()=>void navigate(index+1)}>Next</button><button disabled={busy} onClick={()=>void answer(q.answer.optionId,false,Math.min(index+1,attempt.questions.length-1))}>Save & Next</button><button disabled={busy} onClick={()=>void answer(q.answer.optionId,true,Math.min(index+1,attempt.questions.length-1))}>Mark for Review & Next</button></div></section>
 <aside className="mock-palette"><h2>Question palette</h2><div className="mock-palette-grid">{attempt.questions.map((item,i)=><button disabled={busy} key={item.id} className={`${state(item)} ${i===index?'current':''}`} aria-label={`Question ${i+1}: ${state(item).replaceAll('-',' ')}`} onClick={()=>void navigate(i)}>{i+1}</button>)}</div><ul className="mock-legend">{[['not-visited','Not visited'],['unanswered','Unanswered'],['answered','Answered'],['review','Marked for review'],['answered-review','Answered + marked']].map(([key,label])=><li key={key}><span className={key}/>{label}</li>)}</ul><p>One overall timer. Free section navigation. Refresh preserves the stored deadline and saved answers.</p><button onClick={()=>setConfirmSubmit(true)} disabled={busy}>Finish attempt</button></aside></div>}
 {confirmSubmit&&!done&&<div className="mock-modal"><section role="dialog" aria-modal="true" aria-label="Confirm test submission"><h2>Submit this test?</h2><p>{attempt.questions.filter(q=>q.answer.optionId).length} answered · {attempt.questions.filter(q=>q.answer.markedForReview).length} marked for review. Answers cannot be edited after submission.</p><button disabled={busy} onClick={()=>setConfirmSubmit(false)}>Keep working</button><button disabled={busy} onClick={()=>void submit()}>Confirm submit</button></section></div>}
 </>;
}
function Analysis({rows}:{rows:AnalysisGroup[]}){return <div className="mock-table"><table><thead><tr><th>Area</th><th>Attempted</th><th>Correct</th><th>Accuracy</th><th>Score</th><th>Signal</th></tr></thead><tbody>{rows.map(r=><tr key={r.name}><td>{r.name}</td><td>{r.attempted}/{r.total}</td><td>{r.correct}</td><td>{r.accuracyPercent===null?'—':r.accuracyPercent+'%'}</td><td>{r.score}</td><td>{r.classification}</td></tr>)}</tbody></table></div>;}
