"use client";
import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { apiRequest } from "@/lib/api-client";
type Stage = "email" | "code" | "password" | "done";
export function PasswordRecoveryForm() {
  const router=useRouter();const [stage,setStage]=useState<Stage>("email");const [email,setEmail]=useState("");const [token,setToken]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const data=new FormData(event.currentTarget);try{
    if(stage==="email"){const value=String(data.get("email")).trim();await apiRequest("/auth/forgot-password",{email:value});setEmail(value);setNotice("If that account is active, a six-digit code was sent. Check spam too.");setStage("code");}
    else if(stage==="code"){const result=await apiRequest<{resetToken:string}>("/auth/verify-reset",{email,code:String(data.get("code")).trim()});setToken(result.resetToken);setNotice("Code verified. Create your new password.");setStage("password");}
    else if(stage==="password"){const password=String(data.get("password"));if(password!==String(data.get("confirmPassword")))throw new Error("Passwords do not match.");await apiRequest("/auth/reset-password",{resetToken:token,newPassword:password});setStage("done");setNotice("Password updated. Sign in with your new password.");}
  }catch(e){setError(e instanceof Error?e.message:"Please try again.");}finally{setBusy(false);}}
  return <main className="auth-page"><Link href="/" className="brand"><span className="brand-mark">S</span> Spilton <span className="muted">AI</span></Link><section className="auth-card"><p className="eyebrow">ACCOUNT RECOVERY</p><h1>Reset your password</h1><p className="muted">Use the email registered with your Spilton account.</p>{notice&&<p role="status" className="field-help">{notice}</p>}{error&&<p role="alert" className="error-message">{error}</p>}{stage!=="done"?<form onSubmit={submit}><fieldset disabled={busy}>{stage==="email"&&<label>Email<input name="email" type="email" autoComplete="email" required maxLength={254}/></label>}{stage==="code"&&<label>Six-digit code<input name="code" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" minLength={6} maxLength={6} required/></label>}{stage==="password"&&<><label>New password<input name="password" type="password" autoComplete="new-password" minLength={6} maxLength={128} required/></label><label>Confirm new password<input name="confirmPassword" type="password" autoComplete="new-password" minLength={6} maxLength={128} required/></label></>}<button className="primary-button" type="submit">{busy?"Please wait…":stage==="email"?"Send reset code":stage==="code"?"Verify code":"Save new password"}</button>{stage==="code"&&<button className="secondary-button" type="button" onClick={()=>{setStage("email");setNotice("");setError("");}}>Send a new code</button>}</fieldset></form>:<button className="primary-button" onClick={()=>router.replace("/login")}>Go to sign in</button>}<p className="auth-switch"><Link href="/login">Back to sign in</Link></p></section></main>;
}
