"use client";
import {useEffect,useState, type FormEvent} from 'react';
import {chatRequest} from '@/lib/chat-client';
import './preparation.css';
import {useRouter} from 'next/navigation';
type Space={id:string;name:string;description:string;type:string;isArchived:boolean};
type Topic={id:string;name:string;subject:string;status:string;questionsAttempted:number;questionsCorrect:number;accuracyPercent:number|null};
type Profile={examStageId:string;dailyMinutes:number;level:string;preferredLanguage:string;targetScore:number|null;expectedExamDate:string|null;exam:string;stage:string};
type Dashboard={latestMock?:{id:string;title:string;score:number;accuracyPercent:number|null};recentMockAccuracy?:number|null;profile:Profile|null;topics:Topic[];indicator:number;accuracyPercent:number|null;goals:{id:string;title:string;description:string;status:string;progressPercent:number;targetDate:string|null}[];memories:{id:string;type:string;content:string;isActive:boolean}[];recommendations:{topic:string;reason:string}[];planItems:{id:string;date:string;minutes:number;status:string;topic:string;reason:string}[];recentChats:{id:string;title:string}[];recentDocuments:{id:string;name:string;status:string}[]};
type Catalog={exams:{id:string;name:string}[];stages:{id:string;examId:string;name:string}[]};
export function PreparationPanel({space}:{space:string}){const router=useRouter();
 const [spaces,setSpaces]=useState<Space[]>([]),[data,setData]=useState<Dashboard|null>(null),[catalog,setCatalog]=useState<Catalog>({exams:[],stages:[]}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const query=space?`?spaceId=${space}`:'';const chat=`/chat${space?`?space=${space}`:''}`;

 useEffect(()=>{let alive=true;Promise.all([chatRequest<{items:Space[]}>('/spaces'),chatRequest<Dashboard>('/preparation/dashboard'+query),chatRequest<Catalog>('/preparation/catalog')]).then(([s,d,c])=>{if(alive){setSpaces(s.items);setData(d);setCatalog(c);}}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[query]);
 async function refresh(){setData(await chatRequest<Dashboard>('/preparation/dashboard'+query));setSpaces((await chatRequest<{items:Space[]}>('/spaces')).items);}
 async function action(path:string,method:string,body?:unknown){setBusy(true);setError('');try{await chatRequest(path,method,body);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function values(e:FormEvent<HTMLFormElement>){e.preventDefault();return Object.fromEntries(new FormData(e.currentTarget));}
 const scope={spaceId:space||null};const active=spaces.find(s=>s.id===space);
 return <main className="prep"><header><a href={chat}>✦ Spilton AI · Chat</a><h1>Your preparation workspace</h1><p>Small steps, visible progress. Everything here comes from your saved activity.</p><label>Current Space<select value={space} onChange={e=>{router.push('/prepare'+(e.target.value?'?space='+e.target.value:''));}}><option value="">General</option>{spaces.map(s=><option key={s.id} value={s.id}>{s.name}{s.isArchived?' · Archived':''}</option>)}</select></label><a href={"/government"+(space?"?space="+space:"")}>Government resources</a></header>
 {error&&<p role="alert">{error}</p>}{!data?<p role="status">Loading preparation…</p>:<>
 <section><h2>Choose your target exam</h2><form key={space+JSON.stringify(data.profile)} onSubmit={e=>{const v=values(e);void action('/preparation/profile','POST',{...scope,examStageId:v.stage,dailyMinutes:Number(v.minutes),level:v.level,preferredLanguage:v.language,targetScore:v.score?Number(v.score):null,expectedExamDate:v.date||null});}}><label>Exam and stage<select name="stage" required defaultValue={data.profile?.examStageId||''}><option value="" disabled>Select your exam</option>{catalog.stages.map(s=><option key={s.id} value={s.id}>{catalog.exams.find(e=>e.id===s.examId)?.name} · {s.name}</option>)}</select></label><label>Daily study minutes<input name="minutes" type="number" min={15} max={480} defaultValue={data.profile?.dailyMinutes||60} required/></label><label>Preparation level<select name="level" defaultValue={data.profile?.level||'BEGINNER'}><option>BEGINNER</option><option>INTERMEDIATE</option><option>ADVANCED</option></select></label><label>Preferred language<select name="language" defaultValue={data.profile?.preferredLanguage||'English'}><option>English</option><option>Telugu</option><option>Hindi</option></select></label><label>Target score (optional)<input name="score" type="number" min={1} max={10000} defaultValue={data.profile?.targetScore||''}/></label><label>Expected exam date (optional)<input name="date" type="date" defaultValue={data.profile?.expectedExamDate||''}/></label><button disabled={busy||active?.isArchived}>Save exam profile</button></form><p>Starter study catalog, not a complete or official current syllabus.</p></section>
 <div className="prep-grid"><section><h2>{data.profile?`${data.profile.exam} · ${data.profile.stage}`:'Your preparation progress'}</h2><strong className="prep-score">{data.indicator}%</strong><p>Internal preparation indicator · not a predicted score or rank.</p><details><summary>How this is calculated</summary>Average topic status: Not started 0, Learning 25, Practicing 50, Review 75, Mastered 100. All progress is manually reported.</details><p>Reported accuracy: {data.accuracyPercent===null?'No practice recorded':data.accuracyPercent+'%'}</p><a href={chat}>Ask Spilton</a></section>
 <section><h2>Today’s focus / Weak areas</h2>{data.recommendations.length?data.recommendations.map(r=><p key={r.topic}><b>{r.topic}</b><br/>{r.reason}</p>):<p>Create a profile and record progress to receive explainable recommendations.</p>}</section></div>
 <section><h2>Mock performance</h2>{data.latestMock?<p>{data.latestMock.title} · Latest score {data.latestMock.score} · Recent accuracy {data.recentMockAccuracy===null?"No answered questions":data.recentMockAccuracy+"%"}</p>:<p>No completed mock yet. Scores appear only after a real submitted attempt.</p>}<a href={"/mocks"+(space?"?space="+space:"")}>Mock Tests · Practice Weak Areas · Attempt History</a></section><section><h2>Spaces</h2><form onSubmit={e=>{const v=values(e);void action('/spaces','POST',{name:v.name,description:v.description,type:v.type});}}><label>Space name<input name="name" required maxLength={100}/></label><label>Description<input name="description" maxLength={500}/></label><label>Purpose<select name="type"><option>EXAM</option><option>LEARNING</option><option>CAREER</option><option>GENERAL</option></select></label><button disabled={busy}>Create Space</button></form>
 {active&&<form key={active.id+active.name} onSubmit={e=>{const v=values(e);void action('/spaces/'+active.id,'PATCH',{...active,name:v.name,description:v.description});}}><label>Rename Space<input name="name" defaultValue={active.name} required maxLength={100}/></label><label>Edit description<input name="description" defaultValue={active.description} maxLength={500}/></label><button disabled={busy}>Save Space</button><button type="button" disabled={busy} onClick={()=>void action('/spaces/'+active.id,'PATCH',{...active,isArchived:!active.isArchived})}>{active.isArchived?'Restore Space':'Archive Space'}</button><button type="button" onClick={()=>{if(confirm('Delete this empty Space? Spaces containing saved work must be archived.'))void action('/spaces/'+active.id,'DELETE').then(()=>{router.push('/prepare');});}}>Delete empty Space</button></form>}</section>

 <section><h2>Goals</h2><form onSubmit={e=>{const v=values(e);void action('/preparation/goals','POST',{...scope,title:v.title,targetDate:v.date||null});}}><label>Study goal<input name="title" required maxLength={160}/></label><label>Target date<input type="date" name="date"/></label><button disabled={busy}>Add goal</button></form>{data.goals.map(g=><form key={g.id} onSubmit={e=>{const v=values(e);void action('/preparation/goals/'+g.id,'PATCH',{...g,...scope,progressPercent:Number(v.progress),status:v.status});}}><b>{g.title}</b><label>Progress %<input name="progress" type="number" min={0} max={100} defaultValue={g.progressPercent}/></label><select name="status" aria-label={'Goal status '+g.title} defaultValue={g.status}><option>ACTIVE</option><option>PAUSED</option><option>COMPLETED</option></select><button disabled={busy}>Update goal</button><button type="button" onClick={()=>{if(confirm('Delete this goal?'))void action('/preparation/goals/'+g.id,'DELETE');}}>Delete goal</button></form>)}</section>
 <section><h2>Approved memory</h2><p>No automatic permanent chat memory. Space memory stays here; General preferences and approved facts can apply across Spaces. Never save secrets or credentials.</p><form onSubmit={e=>{const v=values(e);void action('/preparation/memories','POST',{...scope,type:v.type,content:v.content,approved:v.approved==='on'});}}><label>Category<select name="type">{['Preference','StudyPreference','WeakArea','GoalContext','SpaceContext','UserApprovedFact'].map(t=><option key={t}>{t}</option>)}</select></label><label>Preparation context<input name="content" required maxLength={500}/></label><label><input name="approved" type="checkbox" required/> I approve saving this context for future answers</label><button disabled={busy}>Save memory</button></form>{data.memories.map(m=><p key={m.id}><b>{m.type}</b>: {m.content} · {m.isActive?'Active':'Inactive'} <button disabled={busy} onClick={()=>void action('/preparation/memories/'+m.id,'PATCH',{isActive:!m.isActive})}>{m.isActive?'Deactivate':'Activate'}</button><button onClick={()=>{if(confirm('Delete this memory?'))void action('/preparation/memories/'+m.id,'DELETE');}}>Remove memory</button></p>)}</section>
 <section><h2>Progress & manual diagnostic</h2><p>Enter actual practice counts. This is self-reported performance, not a standardized assessment.</p>{data.topics.map(t=><form key={t.id} onSubmit={e=>{const v=values(e);void action('/preparation/progress/'+t.id,'PATCH',{...scope,status:v.status,questionsAttempted:Number(v.attempted),questionsCorrect:Number(v.correct),lastPracticedAt:Number(v.attempted)>0?new Date().toISOString():null});}}><strong>{t.subject} · {t.name}</strong><label>Status<select name="status" defaultValue={t.status}>{['NOT_STARTED','LEARNING','PRACTICING','REVIEW','MASTERED'].map(s=><option key={s}>{s}</option>)}</select></label><label>Attempted<input name="attempted" type="number" min={0} max={1000000} defaultValue={t.questionsAttempted}/></label><label>Correct<input name="correct" type="number" min={0} max={1000000} defaultValue={t.questionsCorrect}/></label><button disabled={busy}>Save progress</button></form>)}</section>
 <section><h2>Study Plan</h2><form onSubmit={e=>{const v=values(e);void action('/preparation/plans','POST',{...scope,startDate:v.date,days:Number(v.days)});}}><label>Start date<input name="date" type="date" required defaultValue={new Date().toLocaleDateString('en-CA')}/></label><label>Days<input name="days" type="number" min={1} max={14} defaultValue={7}/></label><button disabled={busy||!data.profile}>Generate study plan</button></form>{!data.planItems.length&&<p>No saved plan yet.</p>}{data.planItems.map(i=><form key={i.id} onSubmit={e=>{const v=values(e);void action('/preparation/plan-items/'+i.id,'PATCH',{date:v.date,minutes:Number(v.minutes),status:v.status});}}><strong>{i.topic}</strong><small>{i.reason}</small><label>Date<input name="date" type="date" defaultValue={i.date} required/></label><label>Minutes<input name="minutes" type="number" min={5} max={480} defaultValue={i.minutes}/></label><select name="status" aria-label={'Plan status '+i.topic} defaultValue={i.status}><option>PLANNED</option><option>DONE</option><option>SKIPPED</option></select><button disabled={busy}>Save plan item</button></form>)}</section>
 <div className="prep-grid"><section><h2>Recent chats</h2>{data.recentChats.map(c=><p key={c.id}><a href={chat+(space?'&':'?')+'c='+c.id}>{c.title}</a></p>)}{!data.recentChats.length&&<p>No conversations in this workspace.</p>}</section><section><h2>Recent documents</h2>{data.recentDocuments.map(d=><p key={d.id}>{d.name} · {d.status} <select aria-label={"Move "+d.name+" to Space"} value={space} onChange={e=>void action("/documents/"+d.id,"PATCH",{spaceId:e.target.value||null})}><option value="">General</option>{spaces.filter(s=>!s.isArchived).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></p>)}<a href={chat}>Upload or select documents in chat</a></section></div>
 </>}</main>;
}
