using System.ComponentModel.DataAnnotations;
using System.Text.RegularExpressions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.RateLimiting;
using Microsoft.EntityFrameworkCore;
using Spilton.Api.Data;
namespace Spilton.Api.Preparation;
public sealed record ProfileRequest(Guid? SpaceId,Guid ExamStageId,[Range(15,480)]int DailyMinutes,[Required,StringLength(20)]string Level,[Required,StringLength(30)]string PreferredLanguage,[Range(1,10000)]int? TargetScore=null,DateOnly? ExpectedExamDate=null,DateOnly? StartDate=null);
public sealed record GoalRequest(Guid? SpaceId,[Required,StringLength(160)]string Title,[StringLength(600)]string Description="",DateOnly? TargetDate=null,[Range(0,100)]int ProgressPercent=0,[StringLength(20)]string Status="ACTIVE");
public sealed record MemoryRequest(Guid? SpaceId,[Required,StringLength(30)]string Type,[Required,StringLength(500)]string Content,bool Approved);
public sealed record MemoryUpdate(bool IsActive);
public sealed record ProgressRequest(Guid? SpaceId,[Required,StringLength(20)]string Status,[Range(0,1000000)]int QuestionsAttempted,[Range(0,1000000)]int QuestionsCorrect,[Range(0,100)]int? ConfidenceScore=null,DateTimeOffset? LastPracticedAt=null);
public sealed record PlanRequest(Guid? SpaceId,DateOnly StartDate,[Range(1,14)]int Days=7);
public sealed record PlanItemRequest(DateOnly Date,[Range(5,480)]int Minutes,[Required,StringLength(20)]string Status);
[ApiController,Authorize(Roles="User"),Route("api/preparation"),RequestSizeLimit(15000),EnableRateLimiting("chat"),ResponseCache(NoStore=true,Location=ResponseCacheLocation.None)]
public sealed class PreparationController(AppDbContext db,ScopeGuard scopes,PreparationService preparation):ControllerBase
{
    private Guid UserId=>Guid.Parse(User.FindFirst("sub")!.Value);
    private Task<bool> Allowed(Guid? space,CancellationToken ct,bool write=true)=>scopes.Allowed(UserId,space,write,ct);
    [HttpGet("catalog")]
    public async Task<IActionResult> Catalog(CancellationToken ct)=>Ok(new{notice="Starter topic catalog for organizing preparation; not a complete or official current syllabus.",exams=await db.Exams.AsNoTracking().ToListAsync(ct),stages=await db.ExamStages.AsNoTracking().Select(s=>new{s.Id,s.ExamId,s.Name}).ToListAsync(ct)});
    [HttpGet("dashboard")]
    public async Task<IActionResult> Dashboard([FromQuery]Guid? spaceId,CancellationToken ct)
    {
        if(!await Allowed(spaceId,ct,false))return NotFound();var profile=await preparation.Profile(UserId,spaceId,ct);var topics=await preparation.Topics(profile,ct);
        var goals=await db.Goals.AsNoTracking().Where(g=>g.UserId==UserId&&g.SpaceId==spaceId).OrderByDescending(g=>g.UpdatedAt).Take(50).Select(g=>new{g.Id,g.SpaceId,g.Title,g.Description,g.TargetDate,g.Status,g.ProgressPercent,g.CreatedAt,g.UpdatedAt}).ToListAsync(ct);
        var goalEntities=await db.Goals.AsNoTracking().Where(g=>g.UserId==UserId&&g.SpaceId==spaceId&&g.Status=="ACTIVE").Take(50).ToListAsync(ct);
        var memories=await db.Memories.AsNoTracking().Where(m=>m.UserId==UserId&&m.SpaceId==spaceId).OrderByDescending(m=>m.UpdatedAt).Take(50).Select(m=>new{m.Id,m.SpaceId,m.Type,m.Content,m.Source,m.IsActive,m.CreatedAt,m.UpdatedAt}).ToListAsync(ct);
        var plan=await db.StudyPlans.AsNoTracking().Where(p=>p.UserId==UserId&&p.SpaceId==spaceId).OrderByDescending(p=>p.CreatedAt).Select(p=>new{p.Id,p.StartDate,p.Days,p.CreatedAt}).FirstOrDefaultAsync(ct);
        var planItems=plan is null?[]:await db.StudyPlanItems.AsNoTracking().Where(i=>i.StudyPlanId==plan.Id).OrderBy(i=>i.Date).ThenBy(i=>i.Topic.Name).Select(i=>new{i.Id,i.Date,i.Minutes,i.Status,i.Reason,topic=i.Topic.Name,subject=i.Topic.Subject.Name}).ToListAsync(ct);
        var attempted=topics.Sum(t=>t.QuestionsAttempted);var correct=topics.Sum(t=>t.QuestionsCorrect);
        var mockHistory=await db.MockAttempts.AsNoTracking().Where(a=>a.UserId==UserId&&a.SpaceId==spaceId&&a.Status=="SUBMITTED").OrderByDescending(a=>a.CompletedAt).Take(10).Select(a=>new{a.Id,title=a.MockTest.Title,score=a.FinalScore,a.AccuracyPercent,a.TimeTakenSeconds,a.Correct,a.Incorrect}).ToListAsync(ct);
        return Ok(new{latestMock=mockHistory.FirstOrDefault(),recentMockAccuracy=mockHistory.Sum(a=>a.Correct+a.Incorrect)>0?Math.Round(100m*mockHistory.Sum(a=>a.Correct)/mockHistory.Sum(a=>a.Correct+a.Incorrect),1):(decimal?)null,profile=profile is null?null:new{profile.Id,profile.SpaceId,profile.ExamStageId,exam=profile.ExamStage.Exam.Name,stage=profile.ExamStage.Name,profile.DailyMinutes,profile.Level,profile.PreferredLanguage,profile.TargetScore,profile.ExpectedExamDate,profile.StartDate},topics,goals,memories,plan,planItems,
            indicator=PreparationService.Indicator(topics),indicatorLabel="Internal preparation indicator — reported topic progress, not a predicted score or rank",questionsAttempted=attempted,accuracyPercent=attempted>0?(double?)Math.Round(100.0*correct/attempted,1):null,recommendations=PreparationService.Recommend(topics,goalEntities,DateTimeOffset.UtcNow).Take(3),
            recentChats=await db.Conversations.AsNoTracking().Where(c=>c.UserId==UserId&&c.SpaceId==spaceId).OrderByDescending(c=>c.UpdatedAt).Take(5).Select(c=>new{c.Id,c.Title,c.UpdatedAt}).ToListAsync(ct),
            recentDocuments=await db.Documents.AsNoTracking().Where(d=>d.UserId==UserId&&d.SpaceId==spaceId&&d.Status!="DELETING").OrderByDescending(d=>d.CreatedAt).Take(5).Select(d=>new{d.Id,name=d.OriginalName,d.Status,d.CreatedAt}).ToListAsync(ct)});
    }
    [HttpPost("profile")]
    public async Task<IActionResult> SaveProfile(ProfileRequest request,CancellationToken ct){if(!await Allowed(request.SpaceId,ct))return NotFound();if(!new[]{"BEGINNER","INTERMEDIATE","ADVANCED"}.Contains(request.Level)||!new[]{"English","Telugu","Hindi"}.Contains(request.PreferredLanguage))return BadRequest(new{title="Choose a supported preparation level and language."});if(!await db.ExamStages.AnyAsync(s=>s.Id==request.ExamStageId,ct))return BadRequest(new{title="Unknown exam stage."});var p=await db.UserExamProfiles.SingleOrDefaultAsync(p=>p.UserId==UserId&&p.SpaceId==request.SpaceId,ct);if(p is null){p=new(){UserId=UserId,SpaceId=request.SpaceId};db.UserExamProfiles.Add(p);}p.ExamStageId=request.ExamStageId;p.DailyMinutes=request.DailyMinutes;p.Level=request.Level;p.PreferredLanguage=request.PreferredLanguage;p.TargetScore=request.TargetScore;p.ExpectedExamDate=request.ExpectedExamDate;p.StartDate=request.StartDate;p.UpdatedAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync(ct);return Ok(new{p.Id});}
    [HttpPost("goals")]
    public async Task<IActionResult> AddGoal(GoalRequest r,CancellationToken ct){if(!await Allowed(r.SpaceId,ct))return NotFound();if(!new[]{"ACTIVE","COMPLETED","PAUSED"}.Contains(r.Status))return BadRequest(new{title="Invalid goal status."});if(await db.Goals.CountAsync(g=>g.UserId==UserId&&g.SpaceId==r.SpaceId,ct)>=50)return Conflict(new{title="Limit: 50 goals in a workspace."});var g=new Goal{UserId=UserId,SpaceId=r.SpaceId,Title=r.Title.Trim(),Description=r.Description.Trim(),TargetDate=r.TargetDate,ProgressPercent=r.ProgressPercent,Status=r.Status};db.Goals.Add(g);await db.SaveChangesAsync(ct);return Ok(new{g.Id});}
    [HttpPatch("goals/{id:guid}")]
    public async Task<IActionResult> UpdateGoal(Guid id,GoalRequest r,CancellationToken ct){var g=await db.Goals.SingleOrDefaultAsync(g=>g.Id==id&&g.UserId==UserId,ct);if(g is null||g.SpaceId!=r.SpaceId||!await Allowed(g.SpaceId,ct))return NotFound();if(!new[]{"ACTIVE","COMPLETED","PAUSED"}.Contains(r.Status))return BadRequest(new{title="Invalid goal status."});g.Title=r.Title.Trim();g.Description=r.Description.Trim();g.TargetDate=r.TargetDate;g.ProgressPercent=r.ProgressPercent;g.Status=r.Status;g.UpdatedAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync(ct);return NoContent();}
    [HttpDelete("goals/{id:guid}")]
    public async Task<IActionResult> DeleteGoal(Guid id,CancellationToken ct){var g=await db.Goals.SingleOrDefaultAsync(g=>g.Id==id&&g.UserId==UserId,ct);if(g is null)return NotFound();db.Goals.Remove(g);await db.SaveChangesAsync(ct);return NoContent();}
    [HttpPost("memories")]
    public async Task<IActionResult> AddMemory(MemoryRequest r,CancellationToken ct){if(!await Allowed(r.SpaceId,ct))return NotFound();if(!r.Approved)return BadRequest(new{title="Confirm that you want this preparation context saved."});if(!new[]{"Preference","StudyPreference","WeakArea","GoalContext","SpaceContext","UserApprovedFact"}.Contains(r.Type))return BadRequest(new{title="Invalid memory category."});if(Regex.IsMatch(r.Content,@"(?i)password|passcode|\bOTP\b|api[ _-]?key|\bsecret\b|credit.?card|bank.?account|gsk_|sk-[a-z0-9]{8}|(?:\d[ -]?){13,19}"))return BadRequest(new{title="Do not store passwords, keys, OTPs or financial credentials as memory."});if(await db.Memories.CountAsync(m=>m.UserId==UserId&&m.SpaceId==r.SpaceId,ct)>=50)return Conflict(new{title="Limit: 50 saved memory items per workspace."});var m=new Memory{UserId=UserId,SpaceId=r.SpaceId,Type=r.Type,Content=r.Content.Trim()};db.Memories.Add(m);await db.SaveChangesAsync(ct);return Ok(new{m.Id});}
    [HttpPatch("memories/{id:guid}")]
    public async Task<IActionResult> ToggleMemory(Guid id,MemoryUpdate r,CancellationToken ct){var m=await db.Memories.SingleOrDefaultAsync(m=>m.Id==id&&m.UserId==UserId,ct);if(m is null||!await Allowed(m.SpaceId,ct))return NotFound();m.IsActive=r.IsActive;m.UpdatedAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync(ct);return NoContent();}
    [HttpDelete("memories/{id:guid}")]
    public async Task<IActionResult> DeleteMemory(Guid id,CancellationToken ct){var m=await db.Memories.SingleOrDefaultAsync(m=>m.Id==id&&m.UserId==UserId,ct);if(m is null)return NotFound();db.Memories.Remove(m);await db.SaveChangesAsync(ct);return NoContent();}
    [HttpPatch("progress/{topicId:guid}")]
    public async Task<IActionResult> Progress(Guid topicId,ProgressRequest r,CancellationToken ct){if(!await Allowed(r.SpaceId,ct))return NotFound();var p=await preparation.Profile(UserId,r.SpaceId,ct);if(p is null)return BadRequest(new{title="Create an exam profile first."});if(!await db.Topics.AnyAsync(t=>t.Id==topicId&&t.Subject.ExamStageId==p.ExamStageId,ct))return NotFound();if(!new[]{"NOT_STARTED","LEARNING","PRACTICING","REVIEW","MASTERED"}.Contains(r.Status)||r.QuestionsCorrect>r.QuestionsAttempted||r.LastPracticedAt>DateTimeOffset.UtcNow.AddMinutes(5))return BadRequest(new{title="Check progress status, question counts and practice date."});var record=await db.UserTopicProgress.SingleOrDefaultAsync(t=>t.UserExamProfileId==p.Id&&t.TopicId==topicId,ct);if(record is null){record=new(){UserExamProfileId=p.Id,TopicId=topicId};db.UserTopicProgress.Add(record);}record.Status=r.Status;record.QuestionsAttempted=r.QuestionsAttempted;record.QuestionsCorrect=r.QuestionsCorrect;record.ConfidenceScore=r.ConfidenceScore;record.LastPracticedAt=r.LastPracticedAt;record.UpdatedAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync(ct);return NoContent();}
    [HttpPost("plans")]
    public async Task<IActionResult> GeneratePlan(PlanRequest r,CancellationToken ct){if(!await Allowed(r.SpaceId,ct))return NotFound();var p=await preparation.Profile(UserId,r.SpaceId,ct);if(p is null)return BadRequest(new{title="Set your exam and daily study time first."});if(r.StartDate<DateOnly.FromDateTime(DateTime.Now).AddDays(-1)||r.StartDate>DateOnly.FromDateTime(DateTime.Now).AddYears(2))return BadRequest(new{title="Choose a current or upcoming plan start date."});if(await db.StudyPlans.CountAsync(p=>p.UserId==UserId&&p.SpaceId==r.SpaceId,ct)>=30)return Conflict(new{title="Limit: 30 saved plans per workspace."});var topics=await preparation.Topics(p,ct);var goals=await db.Goals.Where(g=>g.UserId==UserId&&g.SpaceId==r.SpaceId&&g.Status=="ACTIVE").ToListAsync(ct);var ranked=PreparationService.Recommend(topics,goals,DateTimeOffset.UtcNow);var plan=new StudyPlan{UserId=UserId,SpaceId=r.SpaceId,StartDate=r.StartDate,Days=r.Days};var slots=Math.Min(3,Math.Max(1,p.DailyMinutes/20));for(var day=0;day<r.Days;day++){var date=r.StartDate.AddDays(day);if(p.ExpectedExamDate.HasValue&&date>p.ExpectedExamDate.Value)break;for(var slot=0;slot<slots;slot++){var focus=ranked[(slot==0?0:1+(day*(slots-1)+slot-1)%(ranked.Count-1))];plan.Items.Add(new(){TopicId=focus.TopicId,Date=date,Minutes=p.DailyMinutes/slots+(slot==0?p.DailyMinutes%slots:0),Reason=focus.Reason});}}if(plan.Items.Count==0)return BadRequest(new{title="The selected plan starts after your expected exam date."});db.StudyPlans.Add(plan);await db.SaveChangesAsync(ct);return Ok(new{plan.Id});}
    [HttpPatch("plan-items/{id:guid}")]
    public async Task<IActionResult> UpdatePlanItem(Guid id,PlanItemRequest r,CancellationToken ct){var item=await db.StudyPlanItems.Include(i=>i.StudyPlan).SingleOrDefaultAsync(i=>i.Id==id&&i.StudyPlan.UserId==UserId,ct);if(item is null||!await Allowed(item.StudyPlan.SpaceId,ct))return NotFound();if(!new[]{"PLANNED","DONE","SKIPPED"}.Contains(r.Status))return BadRequest(new{title="Invalid plan item status."});item.Date=r.Date;item.Minutes=r.Minutes;item.Status=r.Status;await db.SaveChangesAsync(ct);return NoContent();}
}
