using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.RateLimiting;
using Microsoft.EntityFrameworkCore;
using Spilton.Api.Chat;
using Spilton.Api.Data;
using Spilton.Api.Documents;
using Spilton.Api.Preparation;
namespace Spilton.Api.Government;
public sealed record ResourceRequest(Guid? SpaceId,[Required,StringLength(24)]string Kind,[Required,StringLength(200)]string Title,[StringLength(120)]string Organization="",Guid? DocumentId=null,Guid? ExamId=null,[StringLength(2000)]string? SourceUrl=null,[StringLength(100)]string NotificationNumber="",DateOnly? PublishedDate=null,[Range(1950,2100)]int? Year=null,[StringLength(80)]string Stage="",[StringLength(80)]string Subject="",[StringLength(50)]string Language="",[StringLength(100)]string Shift="",[StringLength(50)]string Category="OTHER",[StringLength(700)]string Summary="",bool RightsConfirmed=false);
public sealed record ResourceUpdate([Required,StringLength(200)]string Title,[Required,StringLength(24)]string Status,bool IsSaved);
public sealed record EligibilityRequest([Range(14,100)]int? Age,[StringLength(30)]string? Education,bool ReviewedAllRules=false,bool NeedsRelaxation=false);
public sealed record CompareRequest([Required,MinLength(2),MaxLength(2)]Guid[] Ids);
[ApiController,Authorize(Roles="User"),Route("api/government"),RequestSizeLimit(12000),ResponseCache(NoStore=true,Location=ResponseCacheLocation.None)]
public sealed class GovernmentController(AppDbContext db,ScopeGuard scopes,SourcePolicy sources,IFileStorage storage):ControllerBase
{
 Guid UserId=>Guid.Parse(User.FindFirst("sub")!.Value);
 IQueryable<GovernmentResource> Owned=>db.GovernmentResources.Where(r=>r.UserId==UserId&&(r.DocumentId==null||(r.Document!.UserId==UserId&&r.Document.SpaceId==r.SpaceId&&r.Document.Status=="READY")));
 static object Dto(GovernmentResource r)=>new{r.Id,r.SpaceId,r.ExamId,r.DocumentId,r.Kind,r.Title,r.Organization,r.NotificationNumber,r.SourceUrl,r.SourceType,r.Verification,r.VerifiedAt,r.Status,r.PublishedDate,r.Year,r.Stage,r.Subject,r.Language,r.Shift,r.Category,r.Summary,r.IsSaved,r.CreatedAt,r.UpdatedAt,sourceRank=SourcePolicy.Rank(r.SourceType),availability=r.DocumentId.HasValue?"OWNED_DOCUMENT":"LINK_METADATA_ONLY",metadataNotice="Title, date and classification are manually supplied metadata; only quoted fields have document provenance."};
 [HttpGet("resources")]
 public async Task<IActionResult> List([FromQuery]Guid? spaceId,[FromQuery]string? kind,[FromQuery]string? search,[FromQuery]Guid? examId,[FromQuery]int? year,[FromQuery]int? yearFrom,[FromQuery]string? organization,[FromQuery]string? stage,[FromQuery]string? subject,[FromQuery]string? status,[FromQuery]DateOnly? date,CancellationToken ct){if(!await scopes.Allowed(UserId,spaceId,false,ct))return NotFound();if(yearFrom is <1950 or >2100)return BadRequest(new{title="Choose a valid starting year."});var q=Owned.AsNoTracking().Where(r=>r.SpaceId==spaceId);if(kind is not null)q=q.Where(r=>r.Kind==kind);if(!string.IsNullOrWhiteSpace(search))q=q.Where(r=>r.Title.Contains(search));if(examId.HasValue)q=q.Where(r=>r.ExamId==examId);if(year.HasValue)q=q.Where(r=>r.Year==year);if(yearFrom.HasValue)q=q.Where(r=>r.Year>=yearFrom);if(!string.IsNullOrWhiteSpace(organization))q=q.Where(r=>r.Organization.Contains(organization));if(!string.IsNullOrWhiteSpace(stage))q=q.Where(r=>r.Stage.Contains(stage));if(!string.IsNullOrWhiteSpace(subject))q=q.Where(r=>r.Subject.Contains(subject));if(!string.IsNullOrWhiteSpace(status))q=q.Where(r=>r.Status==status);if(date.HasValue)q=q.Where(r=>r.PublishedDate==date);var rows=await q.OrderByDescending(r=>r.CreatedAt).Take(100).ToListAsync(ct);return Ok(new{items=rows.OrderByDescending(r=>SourcePolicy.Rank(r.SourceType)).Select(Dto),liveSearchAvailable=false,notice="Private manual-source library. No live crawling, freshness guarantee or official deadline monitoring."});}
 [HttpPost("resources"),EnableRateLimiting("library")]
 public async Task<IActionResult> Create(ResourceRequest r,CancellationToken ct){if(!await scopes.Allowed(UserId,r.SpaceId,true,ct))return NotFound();if(!new[]{"NOTIFICATION","PYQ","CURRENT_AFFAIRS"}.Contains(r.Kind)||!SourcePolicy.SafeUrl(r.SourceUrl))return BadRequest(new{title="Choose a supported resource type and a public HTTPS source URL without credentials or an IP address."});if(r.Kind=="CURRENT_AFFAIRS"&&!new[]{"Government Schemes","Economy","Appointments","Awards","Science and Technology","International","Sports","Environment","Defence","Important Reports","OTHER"}.Contains(r.Category))return BadRequest(new{title="Choose a supported current-affairs category."});if(r.Kind=="PYQ"&&!r.RightsConfirmed)return BadRequest(new{title="Confirm that this paper is official/publicly permitted or your own permitted material. Paid coaching copies are not accepted."});if(r.ExamId.HasValue&&!await db.Exams.AnyAsync(e=>e.Id==r.ExamId,ct))return BadRequest(new{title="Unknown exam."});if(await db.GovernmentResources.CountAsync(x=>x.UserId==UserId,ct)>=100)return Conflict(new{title="Development limit: 100 library resources per user."});
  Document? doc=null;await using var locks=new DocumentReadLocks();if(r.DocumentId.HasValue){doc=await db.Documents.SingleOrDefaultAsync(d=>d.Id==r.DocumentId&&d.UserId==UserId&&d.SpaceId==r.SpaceId&&d.Status=="READY",ct);if(doc is null)return NotFound();var gate=await ConversationLock.TryAcquire(db,doc.Id,ct);if(gate is null)return Conflict(new{title="Document is in use. Retry shortly."});locks.Items.Add(gate);}else if(string.IsNullOrWhiteSpace(r.SourceUrl))return BadRequest(new{title="Select a Ready document or register a source URL."});
  var item=new GovernmentResource{UserId=UserId,SpaceId=r.SpaceId,ExamId=r.ExamId,DocumentId=doc?.Id,Kind=r.Kind,Title=r.Title.Trim(),Organization=r.Organization.Trim(),SourceUrl=r.SourceUrl,NotificationNumber=r.NotificationNumber,PublishedDate=r.PublishedDate,Year=r.Year,Stage=r.Stage,Subject=r.Subject,Language=r.Language,Shift=r.Shift,Category=r.Category,Summary=r.Summary,Status=doc is null?"REGISTERED":"ANALYZED"};
  await sources.Apply(item,doc,ct);if(doc is not null&&r.Kind=="NOTIFICATION")item.Fields=EvidenceAnalysis.Extract(await db.DocumentChunks.AsNoTracking().Where(c=>c.DocumentId==doc.Id).ToListAsync(ct));db.GovernmentResources.Add(item);await db.SaveChangesAsync(ct);return Created($"/api/government/resources/{item.Id}",Dto(item));}
 [HttpGet("resources/{id:guid}")]
 public async Task<IActionResult> Get(Guid id,CancellationToken ct){var r=await Owned.AsNoTracking().Include(r=>r.Fields).SingleOrDefaultAsync(r=>r.Id==id,ct);if(r is null)return NotFound();var chunks=r.DocumentId.HasValue?await db.DocumentChunks.AsNoTracking().Where(c=>c.DocumentId==r.DocumentId&&c.Document.UserId==UserId).ToListAsync(ct):[];return Ok(new{resource=Dto(r),fields=r.Fields.OrderBy(f=>f.Name).Select(f=>new{f.Id,f.Name,f.Quote,f.ChunkId,f.Page,f.Section,f.Confidence}),paperAnalysis=r.Kind=="PYQ"?EvidenceAnalysis.Paper(chunks):null,relevance=r.Kind=="CURRENT_AFFAIRS"?EvidenceAnalysis.Relevance(r):null,notice="Detected excerpts require review; missing fields are unknown. Metadata-only URLs have not been fetched. AI analysis requires a Ready owned document."});}
 [HttpPatch("resources/{id:guid}")]
 public async Task<IActionResult> Update(Guid id,ResourceUpdate request,CancellationToken ct){var r=await Owned.SingleOrDefaultAsync(r=>r.Id==id,ct);if(r is null||!await scopes.Allowed(UserId,r.SpaceId,true,ct))return NotFound();if(!new[]{"REGISTERED","ANALYZED","ARCHIVED"}.Contains(request.Status))return BadRequest(new{title="Invalid status. Application open/closed dates must not be inferred from a library status."});if(request.Status=="ANALYZED"&&!r.DocumentId.HasValue)return BadRequest(new{title="A metadata-only URL has not been analyzed."});r.Title=request.Title.Trim();r.Status=request.Status;r.IsSaved=request.IsSaved;r.UpdatedAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync(ct);return NoContent();}
 [HttpGet("resources/{id:guid}/download")]
 public async Task<IActionResult> Download(Guid id,CancellationToken ct){var r=await Owned.Include(r=>r.Document).SingleOrDefaultAsync(r=>r.Id==id&&r.Kind=="PYQ",ct);if(r?.Document is null)return NotFound();Response.Headers.XContentTypeOptions="nosniff";return File(storage.Open(r.Document.StoredName),r.Document.ContentType,r.Document.OriginalName);}
 [HttpDelete("resources/{id:guid}")]
 public async Task<IActionResult> Delete(Guid id,CancellationToken ct){var r=await Owned.SingleOrDefaultAsync(r=>r.Id==id,ct);if(r is null)return NotFound();db.GovernmentResources.Remove(r);await db.SaveChangesAsync(ct);return NoContent();}
 [HttpPost("resources/{id:guid}/eligibility"),EnableRateLimiting("chat")]
 public async Task<IActionResult> Eligibility(Guid id,EligibilityRequest request,CancellationToken ct){var r=await Owned.Include(r=>r.Fields).SingleOrDefaultAsync(r=>r.Id==id&&r.Kind=="NOTIFICATION",ct);if(r is null)return NotFound();if(request.Education is not null&&!new[]{"BELOW_BACHELOR","BACHELOR_OR_HIGHER"}.Contains(request.Education))return BadRequest(new{title="Select a supported education level."});return Ok(new{result=EligibilityEngine.Check(r.Fields.ToList(),new(request.Age,request.Education,request.ReviewedAllRules,request.NeedsRelaxation)),sourceType=r.SourceType,verification=r.Verification,documentId=r.DocumentId});}
 [HttpPost("compare"),EnableRateLimiting("chat")]
 public async Task<IActionResult> Compare(CompareRequest request,CancellationToken ct){if(request.Ids.Distinct().Count()!=2)return BadRequest();var rows=await Owned.AsNoTracking().Include(r=>r.Fields).Where(r=>request.Ids.Contains(r.Id)&&r.Kind=="NOTIFICATION").ToListAsync(ct);if(rows.Count!=2)return NotFound();if(rows[0].SpaceId!=rows[1].SpaceId)return BadRequest(new{title="Select notifications in the same Space for comparison."});return Ok(new{notice="Side-by-side evidence; omissions are unknown, not differences proven by AI.",items=rows.Select(r=>new{resource=Dto(r),fields=r.Fields.Where(f=>new[]{"Qualification","Age","AgeRelaxation","ImportantDates","Fee","SelectionProcess","ExamPattern","Syllabus"}.Contains(f.Name)).Select(f=>new{f.Name,f.Quote,f.Page,f.ChunkId})})});}
 [HttpGet("research-status")]public IActionResult ResearchStatus()=>Ok(new{liveSearchAvailable=false,provider="Manual document/URL registration",notice="Live web research is not connected. Research mode reads selected owned documents only and cannot verify today's latest facts.",stages=new[]{"Reading selected documents","Comparing available evidence","Preparing cited answer"}});
}
