import {test,expect} from '@playwright/test';
test('Space profile, approved memory, plan and progress persist and stay separate',async({page})=>{
 test.setTimeout(120000);await page.goto('/register');await page.getByLabel('Full name',{exact:true}).fill('Prep Browser');await page.getByLabel('Email',{exact:true}).fill(`prep-ui-${Date.now()}@example.test`);await page.getByLabel('Password',{exact:true}).fill('Browser-test-'+Date.now()+'!');await page.getByRole('button',{name:'Create account'}).click();await expect(page).toHaveURL(/chat/);
 await page.goto('/prepare');await expect(page.getByRole('heading',{name:'My Exams',exact:true})).toBeVisible();await page.getByLabel('Space name',{exact:true}).fill('SSC Browser');await page.getByRole('button',{name:'Create Space',exact:true}).click();await expect(page.getByLabel('Current Space').locator('option').filter({hasText:'SSC Browser'})).toHaveCount(1);const id=await page.getByLabel('Current Space').locator('option').filter({hasText:'SSC Browser'}).getAttribute('value');await page.getByLabel('Current Space').selectOption(id!);await expect(page).toHaveURL(new RegExp('space='+id));await expect(page.getByLabel('Rename Space',{exact:true})).toHaveValue('SSC Browser');
 await page.getByLabel('Exam and stage').selectOption({label:'SSC CGL · Tier 1'});await page.getByLabel('Preferred language').selectOption('Telugu');await page.getByRole('button',{name:'Save exam profile'}).click();await expect(page.getByRole('heading',{name:'SSC CGL · Tier 1'})).toBeVisible();
 await page.getByLabel('Preparation context',{exact:true}).fill('Prefer worked examples');await page.getByLabel('I approve saving this context for future answers').check();await page.getByRole('button',{name:'Save memory'}).click();await expect(page.getByText('Prefer worked examples',{exact:false}).last()).toBeVisible();
 await page.getByRole('button',{name:'Generate study plan'}).click();await expect(page.getByRole('button',{name:'Save plan item'})).toHaveCount(21);await page.reload();await expect(page.getByRole('button',{name:'Save plan item'})).toHaveCount(21);
 await page.getByRole('button',{name:'Deactivate',exact:true}).click();await expect(page.getByRole('button',{name:'Activate',exact:true})).toBeVisible();await page.getByLabel('Current Space').selectOption('');await expect(page).toHaveURL(/\/prepare$/);await expect(page.getByRole('heading',{name:'Choose your target exam'})).toBeVisible();await expect(page.getByRole('button',{name:'Activate',exact:true})).toHaveCount(0);
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
});
